### ISSUE TITLE
Host static assets on a CDN

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto.js#103]
Hotlinking to Github static assets hosting doesn't work well with browsers having strong mimetype checks. Also that's probably unfair to Github, so we have to find a proper solution.

**Comment by Natim** [comment]
A simple solution is to use https://rawgit.com/

**Comment by n1k0** [comment]
> A simple solution is to use https://rawgit.com/

[Nope.](https://rawgit.com/faq#rawgit-com-in-production)

**Comment by Natim** [comment]
I means we can use cdn.rawgit.com for tagged release and rawgit.com for master.

**Comment by n1k0** [comment]
Idunno, I'd like to ensure it's allowed by Github first.

**Comment by Natim** [comment]
cdn.rawgit.com footprint on github servers is really low. And github provide rawgit API with throwling so we are safe here. The only limitation is that once the cdn url has been created the file is never ever updated, reason why we should use cdn.rawgit for tags only.

https://rawgit.com/faq#cdn-ttl
