### ISSUE TITLE
Error when server returns 400 error response

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto.js#110]
``Cannot read property 'errno' of null``

**To reproduce**:

```js
var collection = kinto.collection("ZjE1ZjgxODMtOTcyNy00ZDgzLWE2MDEtOTUyMTFlYTIzMzQ5OnMzY3IzdA==-items");
collection.sync();
```

Server will respond:
```
GET https://kinto.dev.mozaws.net/v1/buckets/default/collections/ZjE1ZjgxODMtOTcyNy00ZDgzLWE2MDEtOTUyMTFlYTIzMzQ5OnMzY3IzdA==-items/records

Access-Control-Allow-Origin:*
Connection:keep-alive
Content-Length:167
Content-Type:application/json; charset=UTF-8
Date:Wed, 12 Aug 2015 07:24:54 GMT
Server:nginx/1.4.6 (Ubuntu)

{"errno":107,"message":"path: Invalid record id","code":400,"details":[{"location":"path","name":null,"description":"Invalid record id"}],"error":"Invalid parameters"}
```

Curiously, it looks like in kinto.js code ``response.json()`` is `null`.

**Comment by n1k0** [comment]
Seems this 400 is served with no response JSON body at all, hence why we get a null:

![screen shot 2015-09-04 at 15 43 58](https://cloud.githubusercontent.com/assets/41547/9685039/dc09a6fa-531b-11e5-8b19-ec9cb18e74ad.png)

Code I used for reproduced from the demo page:

```js
var kinto = new Kinto({remote: "https://kinto.dev.mozaws.net/v1"});
var collection = kinto.collection("ZjE1ZjgxODMtOTcyNy00ZDgzLWE2MDEtOTUyMTFlYTIzMzQ5OnMzY3IzdA==-items");
collection.sync({headers: {Authorization: "Basic " + btoa("niko:niko")}});
```

**Comment by Natim** [comment]
It looks like a Browser issue also I have no idea why it would react that way.

**Comment by Natim** [comment]
I have the error and the body, so I suppose we are not passing the right body to the JSON.parse method.

![example](https://cloud.githubusercontent.com/assets/229453/9686031/fe6f1724-5321-11e5-93c3-7bfd0c770d4a.png)

**Comment by n1k0** [comment]
Ok so it appears that this 400 response doesn't have the `Content-Length` header set. I'm gonna fix this along #125.

**Comment by n1k0** [comment]
Hmm, the header is present. But the `access-control-expose-headers` is missing in that response, that explains why client code can't access it. This is a server bug :)

**Comment by Natim** [comment]
> This is a server bug :)
Youpi :)
