### ISSUE TITLE
Install from github branch

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto.js#112]
With the current strategy (see #105), kinto cannot be installed from a github branch.

```diff
diff --git a/package.json b/package.json
index 1f15289..fe037bf 100644
--- a/package.json
+++ b/package.json
@@ -38,7 +38,7 @@
     "karma-webpack": "^1.7.0",
-    "kinto": "^1.0.0-rc.3",
+    "kinto": "git://github.com/mozilla-services/kinto.js.git#db-prefix",
     "mocha": "^2.2.5",
```

``Module not found: Error: Cannot resolve module 'kinto'``.

**Comment by n1k0** [comment]
That'd mean versioning the compiled lib files, which is probably not a good idea. I don't have any other idea, unfortunately :/

**Comment by n1k0** [comment]
The only way to solve this would be to run a [postinstall script]() compiling the babel files into `lib/` after the package is installed; though that's gonna be deprecated in npm eventually, and running code on users system is discouraged by npm maintainers.

See this issue for reference https://github.com/npm/npm/issues/4134

Closing until someone offers a viable alternative.
