### ISSUE TITLE
Clarify if 'clearing the collection' affects only client, or client+server

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#114]
Sometimes I will want to remove all the items from the collection on the server.
Other times (actually, probably only when debugging, or maybe when offline and offering the user something like `git checkout -- .` to discard unpushed changes), I only want to flush the cache, to make sync start from zero.
It is not clear to me which one of these two is done by http://kintojs.readthedocs.org/en/latest/api/#clearing-the-collection

**Comment by leplatrem** [comment]
Currently ``collection.clear()`` will only clear the local store (records + last sync etag). Hence, if I'm not wrong, it will behave as ``git checkout --``.

In order to remove all items on the server, so far there is no way to do it from kinto.js. It can be done on the API using a ``DELETE /buckets/{..}/collections/{...}/records`` though.

What would you suggest to implement this ? Adding a ``flush`` option to sync() ? Don't hesitate to write some *dream code*, and we'll iterate on that :)

**Comment by Natim** [comment]
I my opinion, ``collection.clear()`` should mark all records of the collection as deleted and should try to delete them during the next sync.

**Comment by leplatrem** [comment]
> I my opinion, collection.clear() should mark all records of the collection as deleted and should try to delete them during the next sync.

Instead, to be consistent with remote API, I would suggest to have a *bulk delete* method on the collection (with same params as ``list()``).

```js
collection.delete({filters: {complete: true})
```

**Comment by michielbdejong** [comment]
For me, having `collection.clear()` is enough! I just found the phrase 'This will remove all existing records from the collection' in the documentation a bit scary, I was afraid it would wipe the server.

**Comment by michielbdejong** [comment]
Oh, another thing that surprised me just now is that if I call `.clear()` and then call `.sync()`, the records don't reappear. So it's *not* just a flushing of the cache.

**Comment by michielbdejong** [comment]
Work-around to 'flush the cache' on a collection is to call [`indexedDB.deleteDatabase`](http://stackoverflow.com/a/15861765) from the console, using 'bucket/collection' as the databaseName (so for instance 'syncto/history'). That has the effect I was expecting .clear() to have.

**Comment by n1k0** [comment]
> Oh, another thing that surprised me just now is that if I call .clear() and then call .sync(), the records don't reappear.

That's probably a bug.

Also, I don't think it's a good idea to wipe data on the server when `.clear` is called locally — sounds so much catastrophe-prone… Maybe adding an option to clear, eg. `.clear({sync: true})` + proper docs would be enough to avoid embarrassing situations.

**Comment by n1k0** [comment]
While pairing with @ametaireau, we discovered than after `clear()`ing a collection, metadata were kept — namely collection's `lastModified` value; we should probably drop these as well.

**Comment by michielbdejong** [comment]
Yeah, that was probably what caused the behaviour that surprised me.
