### ISSUE TITLE
Accept Syncto base64 record_ids

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto.js#115]
Refs https://github.com/mozilla-services/syncto/issues/6

**Comment by ametaireau** [comment]
I believe one big reason to not doing that was to avoid implementing something without a use case. But now we have one :)

**Comment by michielbdejong** [comment]
I could also imagine a developer wanting to use id's that have meaning in their app. One possible API behavior would be: if the object you store, or that comes from the server, has a field called exactly `'id'`, then it will be used. If not, a UUID string will be assigned.

**Comment by Natim** [comment]
It is exactly what I wanted Kinto.js to do but @n1k0 didn't want mixed ids in the collection.

See discussion we had here: https://github.com/Kinto/kinto.js/issues/28

The decision was to force UUID4 for now to make sure Kinto.js generated id and Kinto server ids where homogeneous and to implement generators on Kinto.js side when we will have the use case (as @ametaireau said we now have one.)

I think the path forward is to:

 - [ ] Implement the Sync generator on Kinto.js side: ``crypto.randomBytes(9).toString('base64')`` + validation-regexp
 - [ ] Update syncto to use the real syncid and no try to convert it in UUID4

**Comment by n1k0** [comment]
> Implement the Sync generator on Kinto.js side

That would mean having Sync specific use-cases supported by Kinto.js, which is something I want to avoid. A custom transformer specific to the Syncto project would be a better strategy imho.

**Comment by Natim** [comment]
Well actually what we need is to have kinto accept any kind of record id and let's have a pluggable record id generator. Then the Syncto generator doesn't need to be in Kinto.js itself.

**Comment by n1k0** [comment]
> Then the Syncto generator doesn't need to be in Kinto.js itself.

Well, how about records created client side? They'd need to generate ids in the right format, right? Or do you mean we could send new local records data then update their ids with the info returned by the server?

**Comment by n1k0** [comment]
Maybe my question is actually what is *a pluggable record id generator*?

**Comment by Natim** [comment]
Yes the idea was to let people plug their generator for new records in Kinto.js which doesn't means the code of the generator is inside Kinto.js

**Comment by michielbdejong** [comment]
As discussed this morning between @Natim, @n1k0 and myself, we can solve this by setitng a custom generator and validator for ID's on a collection -> https://github.com/Kinto/kinto.js/issues/138

**Comment by Natim** [comment]
Closing this as a duplicate of #138
