### ISSUE TITLE
Maybe add fetch-only / push-only option in Collection#sync()

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#116]
The way we use kinto.js for syncing browser history is:
````
data on remote FxSync
<--network-->
data exposed by syncto
<--kinto.js sync-->
local kinto.js collection
<--adapter-->
DataStore 'places' on the device
````
Since the device is already using the 'places' DataStore all over the place, we want to store all data twice, locally. Once in the kinto.js collection, and once in the 'places' DataStore. The 'adapter' compares the two, and decides how to import changes from the kinto.js collection into the DataStore, and export changes from the DataStore to the kinto.js collection.

Before this adapter runs, we want to make sure we have the latest data from remote, so we want to sync fetch-only.

After the adapter runs, we want to push out any changes it made in the kinto.js collection, so we want to sync push-only.

It's not so expensive to push zero changes in the pre-adapter sync and to pull (probably) zero changes in the post-adapter sync, but at the same time it would be nice to be able to just make the first sync fetch-only, and make the second sync push-only

**Comment by Natim** [comment]
I wonder if it is not best to directly sync in the DataStore rather than using a IndexDB in between.
@n1k0 has implemented a storage layer to let you do that: https://github.com/Kinto/kinto.js/pull/92

**Comment by michielbdejong** [comment]
Good point! Can storage adapters be specified per-collection? Or shall I then just use one Kinto instance per collection?

**Comment by Natim** [comment]
At the moment I guess it is a Kinto instance per collection.

**Comment by michielbdejong** [comment]
ok, I'll play around with that approach, thanks!
