### ISSUE TITLE
Should we allow non-string IDs?

### ISSUE THREAD

**Issue by dstaley** [Kinto/kinto.js#1176]
Currently, you can create your own ID schema that uses non-string values as IDs (and the tests have cases that do specifically that). However, if you attempt to sync with a Kinto server, your records will be rejected. (However it's possible this is just a bug in Kinto, since it's likely doing a simple comparison between a string and an int.)

Should this library retain the ability to create ID schemas that use non-string values (and thus can't synchronize with Kinto)?

@leplatrem what do you think?

**Comment by leplatrem** [comment]
I assume that this comes from #1172, and not from a real use-case.

I don't think we should, especially because we don't want to cast ids to integers when pulling records from the server.

And yes, the tests should be converted to strings :(

**Comment by dstaley** [comment]
Sounds good to me!
