### ISSUE TITLE
Is mutating the [[Prototype]] of an object slow?

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#123]
When I include kinto.dev.js into an html file and open that with FxDesktop 41, I see this warning in the console:
````
mutating the [[Prototype]] of an object will cause your code to run very slowly;
instead create the object with the correct initial [[Prototype]] value using
Object.create
       - kinto.dev.js:2170:5
````

Is this something to worry about?

**Comment by n1k0** [comment]
This is triggered by core-js through Babel transpiled code:

- https://github.com/babel/babel/issues/1099
- https://github.com/zloirock/core-js/issues/46

Quoting a comment in that latest issue thread:

> it's only notification about usage setPrototypeOf / __proto__ and does not creates any performance problems.

Closing.
