### ISSUE TITLE
Report http errors in a meaningful way

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#124]
There [are events for](http://kintojs.readthedocs.org/en/latest/api/#events) backoff and deprecated, but what about network timeouts, 401 Unauthorized errors, and 500 Internal server errors from the Kinto servers? Now, these seem to result in a promise rejection by #sync(), but it would be nice to have more meaningful events to handle. For instance, in case of a 401, it might be necessary to obtain a new BrowserID assertion, which the app needs to handle.

**Comment by michielbdejong** [comment]
This (or at least its API definition) is likely to block some work I have planned for this sprint. Anything I can do to help?

**Comment by n1k0** [comment]
> Anything I can do to help?

Yeah, maybe describe a concrete use case, ideally with code or a pointer to it so I can figure out what an ideal API would be :)

**Comment by n1k0** [comment]
(note: you can also start working on a branch and submit it as a PR for a quick review)

**Comment by michielbdejong** [comment]
I found out I can get the HTTP Status code from `sync`'s promise rejection, so I'm no longer blocked. :) Created PR #128 for hinting at this in the docs.
