### ISSUE TITLE
Why is Content-Length header required on Kinto server responses?

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#125]
In https://github.com/Kinto/kinto.js/blob/1deefd244da694b14320c4094c4248e5cdd26be9/test/http_test.js#L109 you test that requests fail if there is no Content-Length header in the http response.

The default for a nodejs server is (I think, or it seems) to respond without a Content-Length header, because this allows streamed response bodies (http/1.1 chunked encoding). I did not find any mention of this in the Kinto/Cliquet docs. Is this by design?

I can work around this by manually adding a Content-Length header to the mock server I'm using, but I thought it was worth a ticket, because the kinto.js code (and its [unit test](https://github.com/Kinto/kinto.js/blob/1deefd244da694b14320c4094c4248e5cdd26be9/test/http_test.js#L109)) seem to contradict the Kinto/Cliquet API documentation at this point.

**Comment by Natim** [comment]
We though a Content-Length missing headers means no response. We used this to decide whether we should try to decode the JSON body or if there where no body.

**Comment by michielbdejong** [comment]
> We though a Content-Length missing headers means no response

It doesn't mean that when chunked transfer encoding is used; in that case, servers are actually even obliged to leave out the Content-Length header, see http://greenbytes.de/tech/webdav/rfc2616.html#rfc.section.4.4:
"Messages MUST NOT include both a Content-Length header field and a non-identity transfer-coding. If the message does include a non-identity transfer-coding, the Content-Length MUST be ignored."

**Comment by n1k0** [comment]
So the question become, how could we detect that the response has no body when it comes to using the `fetch` AS6 API? I couldn't find any other way to check for a body content before running the `.json()` method on the returned response object :/

**Comment by michielbdejong** [comment]
The example on https://fetch.spec.whatwg.org/#fetch-api checks the Content-Type first, and then tries to parse it as JSON. An empty body with an 'application/json' can arguably be treated as a parse error?

**Comment by n1k0** [comment]
> An empty body with an 'application/json' can arguably be treated as a parse error?

That's what I tried to avoid, especially because JSON parse errors are hardly meaningful. I'll investigate this next week (I'm in holidays atm).
