### ISSUE TITLE
Unhandled promise rejection if server response has no 'data' field

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#126]
[This line](https://github.com/Kinto/kinto.js/blob/1deefd244da694b14320c4094c4248e5cdd26be9/src/api.js#L149) assumes that there is a 'data' field in res.json, and if the server forgets to add this field, this leads to an unhandled promise rejection instead of to some sort of 'server error' event which would be nicer.

Of course, this only happens if the Kinto server is broken in that way.

**Comment by n1k0** [comment]
> if the server forgets to add this field

How could this happen? I'm reluctant implementing specific checks for every possible breakage scenario… Hint?

**Comment by michielbdejong** [comment]
ok, fair enough!
