### ISSUE TITLE
Coverage badge is broken

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto.js#127]
Image URL: https://coveralls.io/repos/Kinto/kinto.js/badge.svg?branch=master&service=github

![](https://coveralls.io/repos/Kinto/kinto.js/badge.svg?branch=master&service=github)

Should be the green one.

**Comment by n1k0** [comment]
Seems to have been self-fixed… Oh well, closing.

**Comment by Natim** [comment]
Yes I did :) Travis ci was configured for PR and not pushes, so master commit where not tested.

**Comment by n1k0** [comment]
> Yes I did :) Travis ci was configured for PR and not pushes, so master commit where not tested.

TIL this was even possible… Thanks!
