### ISSUE TITLE
Creating a collection with Kinto.js

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto.js#134]
We need to add a ``kinto.createCollection("colName", data)`` method in order to create collections from Kinto.js

**Comment by Natim** [comment]
We also need a way to update (data + permissions) and delete a collection

**Comment by n1k0** [comment]
> We need to add a kinto.createCollection("colName", data) method in order to create collections from Kinto.js

Collections are lazily created atm, then you can add data with a `Promise.all`call; why would we need a specific collection creation method?

> We also need a way to update (data + permissions)

This is probably a different issue to file. Also, that would heavily depend on #67.

> and delete a collection

Please file a dedicated issue for this as well.

**Comment by Natim** [comment]
> Collections are lazily created atm

This is the case only for the default bucket, which is not the usecase I am having.

**Comment by Natim** [comment]
> This is probably a different issue to file.

Ok I have filed #136 and #137 about that.

**Comment by n1k0** [comment]
> This is the case only for the default bucket, which is not the usecase I am having.

There's a `bucket` option you can pass to the Kinto constructor, which will create (ans sync) the collection for that specific bucket. Isn't it enough?

**Comment by Natim** [comment]
> which will create (and sync) the collection for that specific bucket.

I did not know it would create a missing collection, I will check.

> Isn't it enough?

I would need to be able to specify the data passed to the collection PUT

**Comment by n1k0** [comment]
Remember that Kinto.js is an offline-first client; we shouldn't publish anything except from `#sync()`.

**Comment by Natim** [comment]
> we shouldn't publish anything except from #sync().

For this specific case we may need to discuss the use-case a little, I am not totally opposed to let the user add some creation to the batch list (to be run during the sync procedure) but we should leverage the behavior in case of errors (if the collection is already full of records (created offline) and that the user doesn't have the permission to write on the collection.

Note that we are already doing some synchroneous commands (fetching server configuration), the collection handling is offline first which doesn't mean the collection setup has to be.

**Comment by n1k0** [comment]
> Note that we are already doing some synchroneous commands (fetching server configuration)

This is reading, not writing. I'm cautious remotely writing things outside from `#sync()` because there's a risk of race conditions and other things which are handled just fine in the sync process.

Let's discuss your use case and see how all this could fit together.

**Comment by leplatrem** [comment]
Done in kinto-client https://github.com/Kinto/kinto-client#creating-a-collection
