### ISSUE TITLE
How do I use 13.0 in the browser?

### ISSUE THREAD

**Issue by guanxun14** [Kinto/kinto.js#1352]
Hi, I'm just setting up a new project and wanted to use Kinto for it.

However, including version 13.0.0 of kinto.min.js directly in the browser via a script tag returns a referenceError global not defined error. I suppose this is because this recently-released [version](https://github.com/Kinto/kinto.js/releases) was re-written in TypeScript, since 12.7 is working fine.

Looking up the [history](https://github.com/Kinto/kinto.js/issues/999) of that release:

> One of the biggest drawbacks to migrating to TypeScript is increasing the barrier to entry for developers who aren't familiar with TypeScript. However, this is offset by adding stronger type checking to library internals, which actually makes it easier for developers to contribute high-quality code.

and

> **If Kinto is written in TypeScript, would it be possible to use it without TypeScript?**
> Yes! Even if the project is written in TypeScript, all consumed versions of the library will be written in JavaScript. If you use a TypeScript-aware tool like VS Code, you'll even get type checking for your JavaScript code when interacting with Kinto.

May I have some simple guidance or be pointed to some reference on how may I get this going? At the moment I'm honestly clueless and can't seem to find how to get this to work.

Thank you :)

**Comment by dstaley** [comment]
Thank you for reporting this! It looks like the issue is actually due to our usage of `rollup-plugin-node-builtins`, which I'm actually planning on removing in v14.

In the meantime, I believe if you put `window.global = {};` somewhere before where you load in the script that should get things working. I'll try and get v14 out tomorrow!

**Comment by guanxun14** [comment]
> `window.global = {};`

That does fix it, thanks for the quick response! Looking forward to v14 :)

**Comment by dstaley** [comment]
[v14](https://github.com/Kinto/kinto.js/releases/tag/v14.0.0) is live on npm!
