### ISSUE TITLE
Pluggable ID schema's

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#138]
Normally, Kinto.js will use UUID strings for item ID's, but there are situations where you want to control how these are generated. For instance, if you are importing an existing data set with integer ID's, or some other ID schema. The idea would be something like (just a draft idea, can be improved):

````js
var MyIdSchema = createIdSchema({
  generate: function() {},
  validate: function(id) {}
});
kinto.collection('foo').use(MyIdSchema);
````

Here, `generate` would return a string, and `validate` would return a boolean.
I'll see if I can implement this in a PR.

**Comment by Natim** [comment]
Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1200156

**Comment by michielbdejong** [comment]
Progress: Got a draft implementation in https://github.com/michielbdejong/kinto.js/commit/ff8f6d361dd6e2cc23d71aa849d653239726d6a4 that works against the 6-original-ids branch of syncto; will now do all the doc updating, variable renaming where appropriate, and write some unit tests for it.
