### ISSUE TITLE
Always brace single-line controlled statements

### ISSUE THREAD

**Issue by ametaireau** [Kinto/kinto.js#141]
We should always brace single-lie controlled statements, as stated in the Mozilla dev. coding style.

> Always brace controlled statements, even a single-line consequent of an if else else. This is redundant typically, but it avoids dangling else bugs, so it's safer at scale than fine-tuning.
> — [Developer Coding Style guide](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style#Control_Structures)

**Comment by n1k0** [comment]
We should enforce checking this rule in our eslint config, if possible.
