### ISSUE TITLE
Avoid redownloading changes on Sync

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto.js#144]
Refs: mozilla-services/readinglist#68

Basically, when doing a Batch before syncing, in the next update you will get all the records you've just changed that are already up-to-date with your local version. (When using ``If-Match`` headers to handle races)

We've just landed something, that let you exclude a list of values when syncing: https://github.com/mozilla-services/cliquet/pull/432

This is something we may want to use in kinto.js sync to optimize the second fetch.

**Comment by n1k0** [comment]
That would be basically adding an `exclude` query string parameter to the second fetch for changes request with the already processed record ids, right?

**Comment by leplatrem** [comment]
Using `?exclude_id=id1,id2,id3` it should work.

What is the limit of the URL length by the way ?

**Comment by leplatrem** [comment]
> What is the limit of the URL length by the way ?

Staying under 2000 chars looks like the most reasonable approach ([source](http://stackoverflow.com/a/417184))
