### ISSUE TITLE
Move `Collection#use` to optional second argument of `Kinto#collection`

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#148]
As discussed in #143, change `Collection#use` to be called `Collection#configure` and to take an object with keys instead of looking at the prototypes like it does now. So then instead of:

````js
collection.use(myIdSchema);
collection.use(myRemoteTransformer);
````

it would become:

````js
collection.configure({
  idSchema: myIdSchema,
  remoteTransformers: [ myRemoteTransformer ]
});
````

**Comment by n1k0** [comment]
Putting back a comment from #143 here, where it's actually relevant:

How about supporting passing the config object as an arg to `Kinto#collection`? Eg.

```js
const kinto = new Kinto();
const collection = kinto.collection("foo", {
  idSchema: myIdSchema,
  remoteTransformers: [ myRemoteTransformer ]
});
```

**Comment by michielbdejong** [comment]
Oh, I like that! I'll add a commit to #149 to implement that, so if it's decided that we want that, I can squash it into there.

**Comment by michielbdejong** [comment]
Actually, I see two options:
````js
const kinto = new Kinto();
const fooColl = kinto.collection("foo");
const barColl = kinto.collection("bar", {
  idSchema: myIdSchema,
  remoteTransformers: [ myRemoteTransformer ]
});
````
or:
````js

const kinto = new Kinto();
const fooColl = kinto.collection("foo");
const barColl = kinto.collection({
  name: "bar",
  idSchema: myIdSchema,
  remoteTransformers: [ myRemoteTransformer ]
});
````
@n1k0 @ametaireau Shall I implement one of these two? Which one?

**Comment by n1k0** [comment]
As a collection name is mandatory and config is optional, the first version is probably the one to go with.

**Comment by Natim** [comment]
Yes I agree with what @n1k0 said :) the former looks better.

**Comment by michielbdejong** [comment]
Great, you guys are so fast and responsive! I'll get cracking. :)

**Comment by ametaireau** [comment]
Go for it! :)
