### ISSUE TITLE
Improve consistency of conflict resolution strategies

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto.js#150]
Followup from #108, conflict resolution strategies and related behaviors should be:

- `MANUAL`: Manual conflict handling, raising an error as soon as a first conflict — incoming or outgoing — is detected;
- `CLIENT_WINS`: no precondition headers in PUT and incoming conflicts resolved with local version;
- `SERVER_WINS`: precondition headers and conflicts resolved with remote version.

**Comment by leplatrem** [comment]
As discussed, another aspect of this change would be automatic sync retry with `CLIENT_WINS` and `SERVER_WINS`.

Currently, it's up to the developer to recursively retry to sync until there is no conflict. It is explicit and without dark magics.

Nonetheless, with the `*_WINS` strategies, it makes sense to handle it automatically. ``$ sync -f`` :)

There could be a `maxRetry` option to limit the number of consecutive calls to sync.
