### ISSUE TITLE
Add a CollectionTransformer concept

### ISSUE THREAD

**Issue by almet** [Kinto/kinto.js#154]
For the collection signing, we need a way to alter and retrieve metadata information contained in the collection.

After a quick chat with @n1k0 it seems to make sense to add a concept of `CollectionTransformers`.

You could then define a transformer that would be called before pushing new data to the collection, or just before retrieving new data from the collection.

**Comment by leplatrem** [comment]
How would that differ from #153 ?

**Comment by almet** [comment]
That's a good question. They seem very similar.

The event approach seems to just be a notification system (that can't intercept the logic going on), while the second (this one) can.

Anyway, I don't think we need the two approach at the same time, and we should pick one or the other.

**Comment by leplatrem** [comment]
Implemented in #302
