### ISSUE TITLE
Add a way to extend batch requests

### ISSUE THREAD

**Issue by almet** [Kinto/kinto.js#156]
It might be useful to add requests to the batch, in order to avoid making extra requests.

I'm actually not sure what the best way to do this would be. Maybe the following?

```js
collection.api.on('batch-request', requests => { return requests + newRequest });
collection.api.on('batch-response', responses => { ... });
```

**Comment by Natim** [comment]
I would rather go for the #154 solution.

**Comment by ametaireau** [comment]
They are not related. One allows to batch all requests together and the other one allows to do something when a collection is fetched or pushed.

**Comment by leplatrem** [comment]
I'm closing this since the use-case is already covered with incoming-changes hooks https://github.com/Kinto/kinto.js/pull/302

If I'm wrong, please reopen and rephrase the issue title :)

**Comment by almet** [comment]
As you said, the use case is covered with the incoming changes hooks, *but* it's doing an extra request to do the validation.

I wanted to have have the ability to add new requests to the stack of yet-to-be-made requests for the next batch, in order to avoid the extra request.

That being said, I don't think we should re-open it for now. At least the idea is documented somewhere.
