### ISSUE TITLE
Use Kinto.js + WebCrypto to sign and verify collections

### ISSUE THREAD

**Issue by almet** [Kinto/kinto.js#157]
Experiment around WebCrypto and Kinto.js, in order to sign and verify the collections.

- [x] [Experiment with Web Crypto key generation and signatures](http://almet.github.io/cryptojs/);
- [ ] Plug the Web Crypto experiment with Kinto.js;
- [ ] Elaborate a protocol to serialize the JSON in a deterministic way;
- [ ] Create a client which signs the collection in a different language, and check the validity from JS.

**Comment by leplatrem** [comment]
This could be a whole documentation section about cryptography and integrity.

**Comment by leplatrem** [comment]
I'll move this issue to kinto-signer instead, where we could document how to use WebCrypto to verify records.
