### ISSUE TITLE
Non-empty syncResults.updated when syncing to an empty remote collection

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#160]
When you run `go()` in the console of http://michielbdejong.github.io/kinto-encrypter-les-donnees/ you see the syncUp step (which uploads data to an empty collection on the public test server) results in:
````
Sync up Object { ok: true, lastModified: 1442328395941, errors: Array[0], 
created: Array[0], updated: Array[1], deleted: Array[0], published: Array[1], 
conflicts: Array[0], skipped: Array[0], resolved: Array[0] }
````
Here, the `published` array contains the encrypted data (which makes sense, I think), but the `updated` array contains that same element. It also happens if you don't use a RemoteTransformer. Is this because `_synced: true` is updated on that record?

**Comment by n1k0** [comment]
> Is this because `_synced: true` is updated on that record?

[Yes](https://github.com/Kinto/kinto.js/blob/82b00c26ce754058ef013ded37e025583ef926f8/src/collection.js#L337-L339). Do you feel it shouldn't be that way?

**Comment by michielbdejong** [comment]
Hm, if I think more about it, there are lots of different cases, in the cross-product of {incoming,outgoing,conflict,resolved,skipped} with {create,update,delete} and {ok,error}. I would expect syncResults to contain the following (covering each combination once):
* errors: {incoming,outgoing,conflict,resolved,skipped} x {create,update,delete} x {error}
* created: {incoming} x {create} x {ok}
* updated: {incoming} x {update} x {ok}
* deleted: {incoming} x {delete} x {ok}
* published: {outgoing} x {create,update,delete} x {ok}
* conflicts: {conflict} x {create,update,delete} x {ok}
* resolved: {resolved} x {create,update,delete} x {ok}
* skipped: {skipped} x {create,update,delete} x {ok}

Here, the first dimensions ({incoming,outgoing,conflict,resolved,skipped}) would be:
* incoming - the record was only changed remotely
* outgoing - the record was only changed locally
* conflict - if the record was changed both locally and remotely, and the conflict was not resolved automatically.
* resolved - if the record was changed both locally and remotely, but the conflict was resolved automatically.
* skipped - *almost* the same as resolved, except that this is the special case where `conflict.local` and `conflict.remote` are identical (both deleted, both created equally, both updated equally), and so we don't even want to call this a "conflict", because its resolution strategy is moot.

The second dimension is the name of the action (create / update delete), and the third dimension is 'ok' if nothing went wrong, or error if something went wrong, with the network connection (including server backoff?), or a bug in the code, etc. (conflicts are not considered errors, they're business as usual).

I would expect the `ok` field of SyncResults to either mean "zero errors" or "zero errors and zero unresolved conflicts", both make sense as long as it's documented.

**Comment by michielbdejong** [comment]
So yes, I would expect `updated` to only contain records that were changed by an incoming change - no need to also include the records with outgoing changes, they're already listed in `updated`, right?

**Comment by n1k0** [comment]
> So yes, I would expect `updated` to only contain records that were changed by an incoming change

But in this case, it was; don't forget there's a possible second call to `pullChanges` after the push has been performed and records were actually published. Maybe this is a naming issue? Or should we skip listing updates in case they occured during that second call?

Also, I agree we should revisit the structure of the sync result object, and properly document all of its properties. Docs are kinda vague about them atm, and their relevance sometimes feels clunky. In this aspect your case study is super useful, I need to think more about it though.

**Comment by michielbdejong** [comment]
> skip listing updates in case they occured during that second call

Well, if client 1 published something and client 2 is fast enough to update that record in between the first and the second call to `pullChanges`, then I would call that an incoming update.

If the only thing that changed is `_synced: true` (i.e. the record's actual data did not change compared to the value it already had locally), then I feel that should show up in `published` but not in `updated`.

Btw, is the second call to `pullChanges` only there to discover the ETag assigned by the server? That's maybe an inefficiency in the Kinto protocol, then. The remoteStorage protocol responds to a PUT with the ETag header assigned, so you don't have to do a HEAD request after each PUT request just for that.
