### ISSUE TITLE
Handling errors during the this.create step of _importChange

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#165]
If https://github.com/Kinto/kinto.js/blob/163-prevent-lastModified-bump-on-errors/src/collection.js#L378 rejects for one record (e.g. record is not an object, id cannot be validated, disk is full), from how I read the code, it will skip everything after https://github.com/Kinto/kinto.js/blob/163-prevent-lastModified-bump-on-errors/src/collection.js#L393-L413, including the call `pushChanges`.

That seems a bit drastic to me, I feel this should simply be added to `SyncResults#errors`, as a per-record error?

Now, 

Are there tests for e.g. disk full errors from IndexedDB?

**Comment by n1k0** [comment]
> Are there tests for e.g. disk full errors from IndexedDB?

Do you mean checking for `QuotaExceededError`? I think these would be propagated as other errors; if you wish a specific error handling in this case, it's probably a separated issue to file.

**Comment by michielbdejong** [comment]
Yeah, that makes sense.
