### ISSUE TITLE
Avoid checking the server settings for each collection

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#169]
For the FxOS Sync app, currently (or actually after we fix bug [1206694](https://bugzilla.mozilla.org/show_bug.cgi?id=1206694) and [bug 1206695](https://bugzilla.mozilla.org/show_bug.cgi?id=1206695)), even if no data changed on the server, nor locally, each sync cycle incurs `4n+4` requests, for `n` the number of collections (currently three, so 16 requests). They are:

* 4 GET requests to 'hello' URL on http://localhost:8000/v1/, to check the server version
* 1 GET request to meta/global (this is mandatory)
* 3 GET requests to ${collection}/records (one for each collection)
* one OPTIONS request for each of these GET requests, (unavoidable, but can be served statically by Syncto or Kinto)

It seems a bit overkill to check http://localhost:8000/v1/ four times within a few seconds. The load impact on the Syncto or Kinto server is probably minimal, since this is probably just a static page, but these requests need to complete before the next thing happens, so it costs time. Their response looks like this, each time:

````js
{"settings":{"cliquet.batch_max_requests":25},"url":"http:\/\/localhost:8000\/v1\/","documentation":"https:\/\/syncto.readthedocs.org\/","version":"1.0.0.dev0","commit":"ebc27e3","hello":"syncto"}
````

Would it be an option to cache these responses (per server URL) at the Kinto level?

**Comment by Natim** [comment]
> Would it be an option to cache these responses (per server URL) at the Kinto level

Yes we should definitely add Cache headers for that.

**Comment by michielbdejong** [comment]
Oh, then we could rely on the browser's http cache? That would be a nice solution!

**Comment by michielbdejong** [comment]
> * one OPTIONS request for each of these GET requests, (unavoidable, but can be served statically by Syncto or Kinto)

After writing that, I'm not actually sure if they are entirely unavoidable. Opened #170 to remind me to look into that.

**Comment by ametaireau** [comment]
The get on the root should be cached, yes. We could even consider to cache it manually in the code rather than issuing multiple times the same request.

**Comment by n1k0** [comment]
> We could even consider to cache it manually in the code

Well I thought it was cached [already](https://github.com/Kinto/kinto.js/blob/b46207b3b4f4db23950fd8b143f8add14a37551c/src/api.js#L111-L113), though thta's at the api.js level, while we'd visibly want it to be cached at the *global* level (think of two distinct `Kinto` instances)… Maybe has a static property attached to the Kinto class itself (yuk)?

Maybe the design is flawed here, as one *should* be capable of using one single Kinto instance per remote endpoint, whatever per-collection config is used; @michielbdejong, what was the reasoning behind using distinct Kinto instances in your case?

**Comment by michielbdejong** [comment]
I'm not so worried about when you have multiple Kinto instances for the same server, that's probably quite rare. Caching at the API level is fine, but apparently it's not working as designed, then? Will investigate.
