### ISSUE TITLE
Can we avoid OPTIONS preflights on (some) GET requests?

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#170]
I thought it should be possible to do GET requests without incurring a preflight. Maybe it's because of the `Access-Control-Request-Headers: "content-type"` options that the browser decides to do a preflight? In the FxOS sync app it could save one request for each sync cycle if we can at least avoid the pre-flight of the first request, to the http://localhost:8000/v1/ 'hello' URL.

I'll have a look at this.

**Comment by ametaireau** [comment]
[The CORS specification](http://www.w3.org/TR/cors/#simple-method) states there is no need for preflight requests for GET/HEAD/POST if the `ContentType` is one of `application/x-www-form-urlencoded`, `multipart/form-data`, or `text/plain`.

Unfortunately, here, we are asking for `application/json` so the request is not considered "simple" and a preflight request is issued.

I see no acceptable way around this :(

**Comment by michielbdejong** [comment]
Right!
