### ISSUE TITLE
RFC: Merge `kinto-http` into `kinto`

### ISSUE THREAD

**Issue by dstaley** [Kinto/kinto.js#1725]
# Summary
[summary]: #summary

Merge [kinto-http.js](https://github.com/Kinto/kinto-http.js) into [kinto.js](https://github.com/Kinto/kinto.js) and ship as a single npm package.

# Motivation
[motivation]: #motivation

As time as gone on, it's become an increasing burden to maintain two separate tooling codebases for both `kinto.js` and `kinto-http.js` despite the fact that virtually 95% of the tooling is identical. Both packages are built using TypeScript, using almost the same rollup configuration, and tested with Intern. This means that every dependency update has to be done effectively twice: once for `kinto.js` and once again for `kinto-http.js`. Furthermore, there have been incidents where the two packages have gotten out of sync (such as the time when `kinto.js` was using `rollup-plugin-typescript` and `kinto-http.js` had migrated to `@rollup/plugin-typescript`).

Switching to a merged codebase would cut dependabot PRs in half, reducing the time maintainers need to spend reviewing dependency update PRs. This is especially helpful since dependabot removed the ability to have PRs automatically merge.

Finally, `kinto.js` is a consumer of `kinto-http.js`, and as such depends on types from `kinto-http.js`. This means that to land some changes in `kinto.js`, we first need to release a new version of `kinto-http.js`. A merged codebase would allow us to make these changes in lockstep, and allow for more type sharing between the two packages.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

Merging the two libraries can be done relatively simply since so much of the tooling is similar. We can move the actual code base of `kinto-http.js` into the folders of `kinto.js` that make the most sense, and continue to use tools like rollup to produce the special files that we need (for things like Firefox)

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

To start, the `kinto-http.js/src` folder will be relocated to `kinto.js/src/http`. Imports like the following:

```ts
import Api from "kinto-http";
```

will be updated to

```ts
import Api from "./http";
```

Additionally, we'll add a `KintoHttp` export to `kinto.js/src/index.ts`

```ts
export { Api as KintoHttp };
```

Package consumers would then update their code from

```ts
import KintoClient from "kinto-http";
```

to

```ts
import { KintoClient } from "kinto";
```

Tests from `kinto-http.js` would be relocated to `kinto.js/test/http`.

We would add the `geckoBuild` rollup config to `kinto.js/rollup.config.js`:

```ts
const geckoBuild = {
  input: "./src/http/index.fx.ts",
```

This change could _technically_ be performed in a semver minor update, but it would likely be best to just go ahead and release it in a semver major.

# Drawbacks
[drawbacks]: #drawbacks

At first glance, one of the major concerns would be increasing the bundle size for consumers of `kinto.js`. However, due to how `kinto-http.js` is imported, tools like rollup and webpack aren't able to perform tree-shaking on `kinto-http.js`, so consumers of `kinto.js` have always had `kinto-http.js` in their bundle.

On the inverse, consumers who only want `kinto-http.js` would need to rely on tree-shaking to eliminate code from `kinto.js`. This wouldn't impact our Firefox build since we use a special rollup config to generate that bundle.

# Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

One of the alternatives we could pursue would be to host both `kinto.js` and `kinto-http.js` in a single repo as a monorepo, relying on tools like [Lerna]() or [npm workspaces](). However, some of our tooling doesn't seem to like workspaces, so this might take more effort to get working. While we would get some of the benefits of having a shared codebase, it would introduce new rough spots where we'd need to ensure that the correct versions of packages were being consumed and published. From my perspective, pursuing a monorepo would only get us a subset of the gains a fully-merged package would grant us.

# Unresolved questions
[unresolved-questions]: #unresolved-questions

- How important is maintaining git repo history? While we'll always be able to go back to the `kinto-http.js` repo and manually look something up, we likely will lose the ability to `git blame` since merging two independent git histories is quite challenging.

/cc @matt-boris @leplatrem

**Comment by leplatrem** [comment]
Thanks @dstaley for the proposal and the detailed RFC :pray: 

It used to be like that :) The [api module was extracted as kinto-client](https://github.com/Kinto/kinto.js/pull/326) and then [renamed to kinto-http](https://github.com/Kinto/kinto-http.js/pull/102).

I'm not too concerned by the Git history. And as long as we can produce an export of the Firefox build that is not bigger, I'm in favor of merging in order to save maintenance efforts. The current Firefox build is visible here: https://searchfox.org/mozilla-central/source/services/common/kinto-http-client.js

Thanks again for being so thorough Dylan :tada: :tada:

**Comment by dstaley** [comment]
Completed in #1726 :tada:
