### ISSUE TITLE
Storing some records fields only locally?

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#173]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1191773#c45 we identified a need to store some metadata on records in Kinto.js which should not be synced to the remote server, and which should also be left intact if a new version of the record (without our local-only field) comes in from remote.

I'm still thinking if we can maybe find a more elegant solution for this.

**Comment by michielbdejong** [comment]
This feature might not be necessary, we might be able to achieve our goal using a `RemoteTransformer`, see suggestion 4 in https://bugzilla.mozilla.org/show_bug.cgi?id=1207468

**Comment by michielbdejong** [comment]
Actually after https://github.com/mozilla-b2g/gaia/pull/32164 it's quite easy - since we will only ever be uploading the `id` and (with encryption) `payload` fields of each record, we can easily add other fields with all the meta-data we want to each record, and as long as it's outside the payload, we can be pretty sure (if there are no bugs and we leave them intact in our conflict handlers) that they will stay in the local copy.

**Comment by leplatrem** [comment]
Currently the `_status` is concerned. It could relatively easy to add a collection parameter specifying the fields names to strip before sync

See:
https://github.com/Kinto/kinto.js/blob/a3fb2fa55029353059747d5b40db45e8a932b9a9/src/collection.js#L787-L789

And:
https://github.com/Kinto/kinto.js/blob/a3fb2fa55029353059747d5b40db45e8a932b9a9/src/collection.js#L136
