### ISSUE TITLE
Consistent reported errors formatting in sync result object

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto.js#176]
Quoting @michielbdejong in #174:

> One a side node (maybe for a follow-up): it's a pity that the error format [for outgoing](https://github.com/Kinto/kinto.js/blob/165-expose-per-record-import-errors/src/api.js#L207-L211) is so different from the errors format [for incoming](https://github.com/Kinto/kinto.js/blob/165-expose-per-record-import-errors/src/collection.js#L440), but with this patch  at least all incoming errors have the same format, regardless of whether they come from e.g. `RemoteTransformer#decode` or from e.g. `IdSchema#verify`.

**Comment by michielbdejong** [comment]
Maybe something like adding `type: 'incoming'` to one, and `type: 'outgoing'` woud already help a lot to clarify the situation. Might be worth addressing this before freezing 1.0, since it's a small issue, and it's about the definition of the API.
