### ISSUE TITLE
Expose transactions from Adapters

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#177]
In order to make better use of IndexedDB transactions (one transaction per operation is superslow), a first step would be exposing transactions from Adapters. Severall syntax ideas are possible, @n1k0 and I were already brainstorming on irc. Here is just one example syntax (sorry for the raw braindump):

Instead of:
````js
Promise.all([
  adapter.create({ id: 0, data: 'foo' }),
  adapter.create({ id: 1, data: 'bar' })
]).then(results => console.log(results), err => console.error(err));
````
it could be:
````js
adapter.batch([
  'create', { id: 0, data: 'foo' },
  'create', { id: 1, data: 'bar' }
]).then(results => console.log(results), err => console.error(err));
````

The way to implement it in current IDB adapter could be something like:
* call `this.open`,
* call `prepare`,
* execute all the operations, using the transaction and store objects from `prepare`,
* Pass the results through `Promise.all`.

We have to look at what happens if different arguments need to be passed to `prepare`, maybe operations have to be grouped per `store`, and then `Promise.all` all the results from all the `store`s.

Since the current operations (`create`, `update`, etc.) in the IDB adapter already call open & prepare, they could be proxies to `_create`, `_update`, etc. functions, that execute the actual actions. So a bit of refactoring there, probably.

The `BaseAdapters` can probably implement this easily using just `Promise.all`, to keep other adapters compatible.

**Comment by n1k0** [comment]
> We have to look at what happens if different arguments need to be passed to prepare

How about using an higher order function?:

```js
const batch = adapter.transaction("storeName");
batch([
  'create', { id: 0, data: 'foo' },
  'create', { id: 1, data: 'bar' }
]).then(results => console.log(results), err => console.error(err));
```

Still I'm not super easy with the `[action, data, action, data, …]` mixed array. How about `.batch()` being smart enough to alow something like this?

```js
const batch = adapter.batch("storeName");
batch([
  batch.create({ id: 0, data: 'foo' }),
  batch.create({ id: 1, data: 'bar' }),
  batch.delete(1),
  batch.update({ id: 0, data: 'baz' })
])
  .then(results => console.log(results))
  .catch(err => console.error(err));
```

Here `batch.create` would simply call `store.add` with the provided data, still using the initiated transaction. Am I talking crazy here? :)

**Comment by n1k0** [comment]
[Here](https://github.com/Kinto/kinto.js/compare/172-bulk-operations)'s a sample draft initial implementation of what I just suggested above. Thoughts?

**Comment by n1k0** [comment]
Another option:

```js
adapter.batch("storeName", (create, update, delete) => {
  create({ id: 0, data: 'foo' });
  create({ id: 1, data: 'bar' });
  delete(1);
  update({ id: 0, data: 'baz' });
})
  .then(results => console.log(results))
  .catch(err => console.error(err));;
```

**Comment by michielbdejong** [comment]
We are not currently exposing the option to set custom `storeName`, right? So then I also wouldn't expose it in `adapter.batch`?

Are there situations where we need to see the individual results of operations? For instance, `create` and `update` return the record, and `delete` returns the id. Maybe you could use `Promise.all` in line https://github.com/Kinto/kinto.js/blob/1bfe8d61c7b09d2d2d2dea06597e2e515bc69ee9/src/adapters/IDB.js#L92 and still be able to return those individual operation results?
