### ISSUE TITLE
is it currently being maintained?

### ISSUE THREAD

**Issue by uma-uc** [Kinto/kinto.js#1885]
I don't see any updates. Please confirm if it's being actively worked on and maintained

**Comment by leplatrem** [comment]
This library was initialized used and maintained by Mozilla. It's not the case anymore, and for a couple of years now, the library has been maintained by @dstaley 

It is not in active development, but like "sustain" mode.

If you are looking into this library to use in a production project, you may have to be ready to dive in the implementation, open pull-requests and refresh some parts. We would be willing to review your submissions though :)
