### ISSUE TITLE
Remove unneeded external dependencies

### ISSUE THREAD

**Issue by mozmark** [Kinto/kinto.js#190]
There are a number of libraries and adapters which are loaded by Kinto that will never be used in some circumstances. E.g. polyfills such as isomorphic fetch are not required where a real fetch implementation exists, kinto.js running as privileged JS will not need IDB or local storage adapters.

Can we re-work so such dependencies are injected in, allowing separate distributed scripts to be prepared for different intended uses?

**Comment by n1k0** [comment]
As per IRC discussion

> mgoodwin: kinto.js seems to include Buffer - is that just because it's a dep. of deep-eql? If so, might you be OK with us shipping a light version version of deep-eql that doesn't use it?
> mgoodwin: (about 50% of the outout file is Buffer related - which seems excessive. Also, it does funky things with mutating object prototypes which is bad for perf)

**Comment by n1k0** [comment]
At first glance, [browserify's `browser` field](https://github.com/substack/browserify-handbook#browser-field) is what we need here; but:

> The browser field only applies to the current package. Any mappings you put will not propagate down to its dependencies or up to its dependents.

So we'll have to ship our own version of `deep-eql`, I'm afraid.
