### ISSUE TITLE
npm run dist not consistent on my machine

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#191]
I get different build results from @n1k0 (even after `rm -r node_modules ; npm install`). We should work out where these differences come from.

**Comment by n1k0** [comment]
Even myself, switching between node version (0.12, 4, 4.1) I'm getting different builds… Hard to figure out why is this precisely.

**Comment by leplatrem** [comment]
Related #181

**Comment by leplatrem** [comment]
Can we close this?

**Comment by michielbdejong** [comment]
yep!
