### ISSUE TITLE
Run inside a ServiceWorker

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#196]
Running Kinto.js inside a ServiceWorker will have two advantages:

* Not [blocking the main thread when accessing IndexedDB](http://nolanlawson.com/2015/09/29/indexeddb-websql-localstorage-what-blocks-the-dom/)
* [Background sync](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API#Other_use_case_ideas)

Of course, an app developer could take kinto.js and put it inside a ServiceWorker, and maybe that's the right approach - if it is, we should write a blogpost that shows how to do this!

**Comment by ametaireau** [comment]
Yes ! We should try to make it work, it seems to make a lot of sense !

**Comment by n1k0** [comment]
We should first investigate what may possibly prevent kinto.js to run within a service worker. As we don't have any other platform dependency than indexedDB, we may be just all fine indeed. Will test today.

**Comment by n1k0** [comment]
> Will test today.

I lied :) 

@leplatrem managed to run kinto.js into a service worker in his [kinto-offline-leaflet](https://github.com/leplatrem/kinto-offline-leaflet) demo, so I think we know it works.

I don't want to support service workers in the kinto.js library itself to keep the dependency graph short, this should probably be handled by a third party utility, if that's even necessary.

**Comment by leplatrem** [comment]
> @leplatrem managed to run kinto.js into a service worker

Not true :) In the demo, the service worker is in charge of caching the map tiles (background) for offline access.

But we can still write a blogpost or a tutorial :) Opened https://github.com/mozilla-services/servicedenuages.fr/issues/95

**Comment by n1k0** [comment]
> Not true :)

Woops, as often my memories lied. We should probably file an issue on the servicedenuage repository then (I'm trying to reduce the amount of non-directly-related issues in this very repository).
