### ISSUE TITLE
reject instead of throw if item not found in Collection#get

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#200]
In https://github.com/Kinto/kinto.js/blob/master/src/collection.js#L371 an error is thrown if the item is not found. This means we need to wrap `myCollection.get` in a try-catch block, which is not so nice.

There might be other places in the code where the same pattern is happening?

**Comment by michielbdejong** [comment]
Wait, I think this bug makes no sense, the `throw` is already inside a `.then` so should actually work correctly.

**Comment by n1k0** [comment]
Yeah, throwing from within a promise callback rejects it, so I think we're safe here.

**Comment by michielbdejong** [comment]
Yes, it was just a bug in my own code. Sorry for the false alarm. :)
