### ISSUE TITLE
Move firefox entry point and storage to kinto.js

### ISSUE THREAD

**Issue by mozmark** [Kinto/kinto.js#212]

**Comment by n1k0** [comment]
Could you please describe a little further the tasks to achieve here? :)

**Comment by mozmark** [comment]
This consists of 3 things:
1) moving the sources for the entry point and the storage adapter into kinto.js
2) changing package.json such that we can just run 'npm run fx-dist' and get the moz-kinto-client created
3) getting the resulting code r+ by yourself and a services peer

You can see 1 and 2 currently in the branch. I'm working on 3 right now.

Your early thoughts on the adapter would be most welcome.

**Comment by n1k0** [comment]
Status update on this one? I feel everything has been done and the issue should be closed.

**Comment by mozmark** [comment]
Yeah, I think this is done. Closing.
