### ISSUE TITLE
bower package

### ISSUE THREAD

**Issue by tardyp** [Kinto/kinto.js#213]
Is it possible to have this package in bower?

**Comment by n1k0** [comment]
It's highly unlikely we support a bower package ([rationale](https://gofore.com/ohjelmistokehitys/stop-using-bower/)). 

Out of curiosity, in your case what are the benefits over using npm?

**Comment by tardyp** [comment]
Well, while bower has its issues browserify has also its own.
Being non dogmatic is imho preferable if you want kinto to become popular.

kinto.js looks for me a good solution to replace firebase in an old low priority monitoring app using firebase.

**Comment by n1k0** [comment]
We're not gonna do this.
