### ISSUE TITLE
Change demo/demo.js to use a bucket

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#233]
Ref https://github.com/Kinto/kinto/issues/231#issuecomment-151583509

**Comment by Natim** [comment]
For the demo we want the data to not be shared between users, so we need to keep the features that comes with default bucket. Also we might fix that on the server side. See https://github.com/Kinto/kinto/pull/233

**Comment by michielbdejong** [comment]
Ah, ok. That will only help in combination with `no-cache` (see http://stackoverflow.com/a/21396547/680454), but I think it would be safe, then.

It does raise questions about Kinto as a protocol, though. In theory, someone could use Kinto.js in combination with their own Kinto-compatible server, forget to implement these two security measures, and still be susceptible to the woes of default buckets and browser caches. Will the protocol spec define both the `no-cache` and the redirects as "MUST"?

Assuming people will copy-paste from the demo app code, you could also just generate a random string as the username in the demo, that would feel  a bit safer to me.

**Comment by Natim** [comment]
> Will the protocol spec define both the no-cache and the redirects as "MUST"?

Yes :)

**Comment by n1k0** [comment]
As commented on #234, we should rather properly document use of custom buckets.

**Comment by michielbdejong** [comment]
ok!
