### ISSUE TITLE
Validate the server http_api_version.

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto.js#268]
kinto.js will ship with an http_api_version it supports and make sure the major is still valid and the minor is greater or equal to the supported one.

Depends on https://github.com/Kinto/kinto/pull/300 and https://github.com/mozilla-services/cliquet/issues/599

**Comment by Natim** [comment]
Blocked by Kinto/kinto#300

**Comment by tarekziade** [comment]
Unblocked

**Comment by leplatrem** [comment]
Done in kinto-client 0.5.0.
