### ISSUE TITLE
ESLint complains about the usage of postMessage with wildcard targets

### ISSUE THREAD

**Issue by ferjm** [Kinto/kinto.js#272]
eslint check:
/Volumes/mozilladev/gaia/shared/js/sync/ext/kinto.min.js: line 217, col 1044, Error - Using postMessage() with wildcard targets is not allowed. (no-wildcard-postmessage/no-wildcard-postmessage)

**Comment by ferjm** [comment]
CC @mozfreddyb

**Comment by julienw** [comment]
Note this is a custom eslint rule we use in Gaia

**Comment by n1k0** [comment]
This is rather strange as Kinto.js own source code doesn't explicitely call `postMessage` at all. Could this be added by Babel or other third-party library to the built file?

Could we add a custom rule for this specific file, which is generated and which we don't have much control on the output?

**Comment by n1k0** [comment]
Appears it's part of babel-core bundled polyfills. Is it a showstopper for you guys, or could we live with it?

**Comment by mozfreddyb** [comment]
While we can certainly add an exception for this file, I find it concerning that a *build step* adds code that posts data to arbitrary origins. So let's first try to remove the postMessage call, if it isn't actually needed.

**Comment by n1k0** [comment]
I think this will be solved by #249, which will provide near-native es6 code with no polyfills at all.

**Comment by n1k0** [comment]
Ah, but FxOS needs es5 code, right. Okay, still need to figure out a proper solution.

**Comment by n1k0** [comment]
Now thinking about it, I think it's possible to just disable bundling the polyfills while keeping the source code being transpiled to es5. And I think this is the actual scope of #249, so it will actually solve this issue I think.

**Comment by mozfreddyb** [comment]
Sweet, thanks!
Should we close this as a duplicate then?

(Btw, FxOS does not need es5, it's a few Gecko versions behind  (depending on release), which still supports a great deal of ES6, but maybe not all.)

**Comment by n1k0** [comment]
I'll keep this specific one open to ensure it's properly tracked :)

**Comment by julienw** [comment]
It's not clear to me where I could have a look at the dist kinto.js ?

My guess is that it could be a polyfill for setImmediate like we have in Gaia: https://github.com/mozilla-b2g/gaia/blob/master/shared/js/setImmediate.js#L137

**Comment by n1k0** [comment]
@julienw https://npmcdn.com/kinto@1.1.1/dist/kinto-1.1.1.js

**Comment by julienw** [comment]
OK, it's actually used for a function called `defer`. It's used on browsers that don't have `MessageChannel`. So on Firefox 40-.

**Comment by n1k0** [comment]
The [noshim](https://npmcdn.com/kinto@1.2.0/dist/kinto-1.2.0.noshim.js) version being now broadly available since #249, I'm closing this.
