### ISSUE TITLE
Expose Kinto collection params for plugin

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto.js#288]
While coding https://github.com/Kinto/kinto.js-plugins/pull/1/files

I realized that the ``bucket_id`` and ``collection_id`` where protected parameters:

    bucket_id = kintoCollection._bucket;
    collection_id = kintoCollection._name;

That's fine, also it might be better to expose them directly:

    bucket_id = kintoCollection.bucket_id;
    collection_id = kintoCollection.collection_id;

**Comment by leplatrem** [comment]
Actually, not really : 
https://github.com/Kinto/kinto.js/blob/master/src/collection.js#L232-L246

(*closing, please reopen if misunderstood*)
