### ISSUE TITLE
Expose Chrome APIs

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto.js#289]
As an experiment, let's see if we can prototype on the top of Kinto.js a Chrome interface. see https://developer.chrome.com/extensions/storage

The interface comes in two objects:

- **chrome.storage.onChanged** : a **StorageChange** objet that can be used to get notifications when the storage has changed
- **chrome.storage.sync**: a **StorageArea** object that can be used to get/set data in the synced storage.

The goal of the prototype is to offer on the client side the API so a chrome extension can sync with a Kinto server.

**Comment by tarekziade** [comment]
See chrome code here https://code.google.com/p/chromium/codesearch#chromium/src/extensions/common/api/storage.json

**Comment by tarekziade** [comment]
The experiment will take place here : https://github.com/tarekziade/kinto-chrome

**Comment by michielbdejong** [comment]
Now moved to https://github.com/Kinto/kinto-chrome/pulls?q=is%3Aopen+is%3Apr
