### ISSUE TITLE
Make the "hacking" page easier to find

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto.js#290]
It took me a bit of time to find http://kintojs.readthedocs.org/en/latest/hacking/

I would like to propose adding in the README.md file and in the index of the documentation a link to the hacking page with the following label : "How to Develop Kinto.js"

**Comment by n1k0** [comment]
"Contributing" would work even better I think.

**Comment by tarekziade** [comment]
yes Contributing sounds great
