### ISSUE TITLE
broken links in the doc

### ISSUE THREAD

**Issue by tarekziade** [Kinto/kinto.js#293]
If you browse this page : 
http://kintojs.readthedocs.org/en/latest/api/#collections

The link for here in the text "Detailed API documentation for Collection#create() is available here."

links to a 404 at 

https://doc.esdoc.org/github.com/Kinto/kinto.js/class/src/collection.js~Collection.html#instance-method-list

**Comment by n1k0** [comment]
For a mysterious reason, esdocs for `Collection` are gone since latest release. /cc @leplatrem

**Comment by leplatrem** [comment]
Fixed with #294
