### ISSUE TITLE
Can Kinto Server push data changes to Client automatically?

### ISSUE THREAD

**Issue by Honghe** [Kinto/kinto.js#297]
Can Kinto Server push data changes to Client automatically?
Just like Firebase.
Thanks!

**Comment by Natim** [comment]
Hello @Honghe,

There are two projects that let you do that: [cliquet-pusher](https://github.com/leplatrem/cliquet-pusher) and soon [kinto-webpush](https://github.com/Kinto/kinto-webpush)

You can plug them quite easily with Kinto.
We do have [some demo](https://github.com/Kinto/kinto/wiki/App-examples) that implements that:

- http://leplatrem.github.io/kinto-demo-calendar/#public
- http://leplatrem.github.io/kinto-telegram-wall/
- http://leplatrem.github.io/cliquet-pusher/

And I have starting to write a kinto.js plugin to ease this a bit more on the client side: https://github.com/Kinto/kinto.js-plugins/pull/1

**Comment by leplatrem** [comment]
We also wrote a tutorial http://kinto.readthedocs.org/en/latest/tutorials/notifications-websockets.html

Closing. Feel free to reopen if you have any doubts!
