### ISSUE TITLE
Leverage the babel rest-object spread plugin

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto.js#304]
In order to avoid the verbosity of `Object.assign`, we should use [ES6 Object Rest/Spread Properties](https://github.com/sebmarkbage/ecmascript-rest-spread).

So instead of writing things like

```js
const updated = Object.assign({}, initial, {_status: "synced"});
```

We'd get

```js
const updated = {...initial, _status: "synced"};
```

This implies enabling the [object rest spread babel plugin](https://www.npmjs.com/package/babel-plugin-transform-object-rest-spread).

**Comment by lavish205** [comment]
@n1k0 in this bug, do we have to replace `{...initial,  {_status: "synced"}};` with `{...initial, _status: "synced"};`?

**Comment by n1k0** [comment]
Yes, the second form is nicer.

**Comment by lavish205** [comment]
I am working on this bug, please assign it to me :)

**Comment by lavish205** [comment]
@n1k0 can you tell me in which files I have to do changes?

**Comment by leplatrem** [comment]
> can you tell me in which files I have to do changes?

Using `git grep "Object.assign"` you can find every occurence.

**Comment by lavish205** [comment]
yeah, done the same thing :)

On Tue, Apr 5, 2016 at 6:38 PM, Mathieu Leplatre <notifications@github.com>
wrote:

> can you tell me in which files I have to do changes?
>
> Using git grep "Object.assign" you can find every occurence.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Kinto/kinto.js/issues/304#issuecomment-205794142>
>



-- 

*Lavish Aggarwal*  | Mozilla Reps
| Google Student Ambassador|
India
