### ISSUE TITLE
304 not detected properly

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#306]
Even if you see a 304 in the Network tab, `res.status === 200` [here](https://github.com/Kinto/kinto.js/blob/b0edc3edd0caf33c0001968982e1b57faa7398f2/src/api.js#L196), and the changes from the last 200 response are returned.

This means that if you try to change a record that was fetched in the previous sync run, this will give a conflict, but shouldn't.

**Comment by michielbdejong** [comment]
I think the thing to do would be to check the `ETag` response header instead of checking for `res.status === 304`, but that's blocked by https://github.com/mozilla-services/cliquet/issues/631

**Comment by michielbdejong** [comment]
Can no longer reproduce the problem after applying https://github.com/Kinto/kinto.js/compare/master...michielbdejong:copy-lastmodified?expand=1

**Comment by n1k0** [comment]
And that makes sense; if the database knows about a last_modified for this record, we should keep it of not provided.

I've already have similar patch in #286, which has strangely never landed. Maybe we should do so :)

**Comment by michielbdejong** [comment]
So even though it's no longer overwriting the last_modified value, we should look at why it's trying to create conflicts with `remote: null` - I think the first problem is that it's repeating a request that returned records before, which I think should never happen, and the second problem is that it's trying to read the body of a 304 response.

**Comment by michielbdejong** [comment]
This seems to be fixed now by a combination of various fixes; can't reproduce anymore.
