### ISSUE TITLE
SRI hash invalid for https://npmcdn.com/kinto@1.2.0/dist/kinto-1.2.0.js

### ISSUE THREAD

**Issue by mozfreddyb** [Kinto/kinto.js#324]
Looking at https://kintojs.readthedocs.org/en/latest/installation/for your SRI hashes, I see your example code which I happily copy and paste:
```html
<script src="//npmcdn.com/kinto@1.2.0/dist/kinto-1.2.0.min.js"
    integrity="sha384-0bOd4qkbXoEiD3nL5tca70NfXWiFprRx1X+xEYVL+0oT/ZlKIoNW0jOcng4I1gGS"
    crossorigin="anonymous">
</script>
```

But then I get:
> None of the "sha384" hashes in the integrity attribute match the content of the subresource.

Trying to calculate the hash on my own:
```curl https://npmcdn.com/kinto@1.2.0/dist/kinto-1.2.0.js | openssl dgst -sha384 -binary | openssl enc -base64 -A ; echo```

gives me
> rn0oNAl6rWA/VxPyRivzf9Ad+LrmqnnaO1V6lujBhVWnA90pJDVR5XFR3GRGx/mM

Did you forget to update the hashes in your docs or does npmcdn mess with your files? :-)

**Comment by leplatrem** [comment]
Well... indeed!

We generated the hashes a-posterio on the tag v1.2.0:

```
$ rm dist/*
$ git co v1.2.0
$ npm run dist
```

```
$ cd dist; for file in $(ls kinto-*.js); do printf "| %-23s | %-64s |\n" ${file} $(echo -n 'sha384-' && cat ${file} | openssl dgst -sha384 -binary | openssl enc -base64); done

| kinto-1.2.0.js          | sha384-zceqJ0xPeewNQ7bpILFGzCtsfoih/dOwop8kxkQ3RCiFuOPeQBC0RGnsaLO0lyhR |
| kinto-1.2.0.min.js      | sha384-0bOd4qkbXoEiD3nL5tca70NfXWiFprRx1X+xEYVL+0oT/ZlKIoNW0jOcng4I1gGS |
| kinto-1.2.0.noshim.js   | sha384-9f0I3QY+QWeXbCgrgvzWfMX/oCL9SHKcoOlACws/VvaARcrVGtgfpIfFvzu1UM4N |
```

But when I take back the files from NPM and compute the hashes, I get the proper values:

```
$ npm install kinto@1.2.0
$ cd node_modules/kinto/dist
$ for file in $(ls kinto-*.js); do printf "| %-23s | %-64s |\n" ${file} $(echo -n 'sha384-' && cat ${file} | openssl dgst -sha384 -binary | openssl enc -base64); done 
| kinto-1.2.0.js          | sha384-rn0oNAl6rWA/VxPyRivzf9Ad+LrmqnnaO1V6lujBhVWnA90pJDVR5XFR3GRGx/mM |
| kinto-1.2.0.min.js      | sha384-aaty4B6Fzw+pZ9DbNdrlGsFu9f8x06+N0aCAXCn1QMpWVgB79PC9KSdWqqagm6E9 |
| kinto-1.2.0.noshim.js   | sha384-WeYjSGsF3rAvWa7r3+tDr/AUzIa3fiWP/xditLak/kw76bQfUtENbx3VhaytTrK+ |
```

Thanks for your feedback, I'll update the documentation, and next time it should be okay since we'll do the whole process in one step :)

**Comment by Natim** [comment]
It is because to run of babel on two differents computer doesn't necessarily return the same compiled and minified file.
