### ISSUE TITLE
Provide previous version of an updated record in sync results

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto.js#335]
/cc @michielbdejong refs https://github.com/Kinto/kinto-chrome/pull/12/files#diff-a7c88e4bf351928799b9036ef131dc57R93

```diff
diff --git a/src/collection.js b/src/collection.js
index 78fcefc..c79b1e5 100644
--- a/src/collection.js
+++ b/src/collection.js
@@ -145,7 +145,7 @@ function importChange(transaction, remote) {
       // status to "synced".
       const synced = markSynced(remote);
       transaction.update(synced);
-      return {type: "updated", data: synced};
+      return {type: "updated", data: synced, previous: local};
     }
     return {
       type: "conflicts",
```

**Comment by Sayli-Karnik** [comment]
Could I work on this one? I'll probably need some more description on what is to be done.

**Comment by n1k0** [comment]
Sure. I'm finding the diff pretty much self-explanatory? It's matter of providing the previous record version as well as the new version in the sync result object for updated records.

**Comment by Sayli-Karnik** [comment]
Do we have to return the previous version in all cases? Currently it is being returned only in this case:
 if (identical) {
      const synced = markSynced(remote);
      transaction.update(synced);
      return {type: "updated", data: synced, previous: local};    //here
    }

**Comment by n1k0** [comment]
You want to provide the previous version of the record every time it's been updated.

**Comment by Sayli-Karnik** [comment]
I have returned the previous version in all cases..could you have a look at my diff?
https://github.com/Kinto/kinto.js/pull/389

**Comment by michielbdejong** [comment]
Nice! That's very useful since now we can fix https://github.com/michielbdejong/gecko-dev/blob/f200a077b7bdb700d60ee0885c5aee169f137057/toolkit/components/extensions/ExtensionStorageSync.jsm#L259-L261 cc @glasserc
