### ISSUE TITLE
Import of data should be done after conflict handling.

### ISSUE THREAD

**Issue by almet** [Kinto/kinto.js#340]
This is a spinoff of https://github.com/Kinto/kinto.js/pull/302. Currently, the import of the data is done and then the conflicts are handled (see https://github.com/Kinto/kinto.js/blob/master/src/collection.js#L572-L583)

**Comment by leplatrem** [comment]
@almet could you detail what was your use-case here?

You'd like to detect conflicts before altering the local db ?

**Comment by almet** [comment]
It is just weird to me to first import data and then fix the conflicts,  it seems more logical to first fix the conflicts and then import so that the database isn't in a conflicting state. 

From what I remember this issue wasn't opened with a specific use case in mind, it was something I wasn't expecting when reading the source code. 

Feel free to close the issue if you think it doesn't make sense, or ask more questions! Cheers

**Comment by leplatrem** [comment]
I think that makes sense. We'll probably have to rethink a bit the sync flow and the conflict API resolution for this though.

**Comment by leplatrem** [comment]
Done in #553
