### ISSUE TITLE
Explicit the difference between kinto.js and kinto-client

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto.js#348]
As per discussion with @davidbgk we should probably answer the question in the documentation:

What is the difference between kinto-client and kinto.js ?

**Comment by davidbgk** [comment]
Actually, I'm often wondering when I discover a project how each repository interacts with others (especially when there are a lot of them), maybe we're missing a technical big picture here?

Something like a new section on http://www.kinto-storage.org/ ? Or is it already documented somewhere?

**Comment by Natim** [comment]
That's exactly what @almet told me when I opened this issue...

**Comment by n1k0** [comment]
Actually I've just spent an hour with @magopian explaining just that, so there's a use case for these high level indeed.

Basically the answer is pretty simple; `kinto-client` is an isomorphic JavaScript HTTP client for the Kinto API, and Kinto.js a library for building Offline-first, synchronized Web applications. The former is a dependency of the latter, meaning Kinto.js communicates with a Kinto server leveraging the kinto-client JavaScript API. kinto-client supports a much broader scope of the Kinto API, while Kinto.js simply uses what it needs from it for collections synchronization purpose.

We now just need to move these three sentences to a more helpful place than this very comment, and kinto-storage.org seems to be the best candidate :)

**Comment by Sayli-Karnik** [comment]
Maybe I could add it to kinto-storage.org?  What is the procedure to add content?

**Comment by Natim** [comment]
The HTML is there: https://github.com/Kinto/kinto-website
