### ISSUE TITLE
Hooks don't need a nested payload object

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto.js#357]
Right now, hooks expect a change payload object formatted that way:

```js
const payload = {changes: {lastModified: unquoted, changes: data}};
```

We could pass either two arguments (changes array and lastModified value), revisit the names or more directly remove the unnecessary level here.

feedback=? @almet

**Comment by almet** [comment]
The second option seems to be the more practical here (pass the two arguments), but then it means that the hooks protocol doesn't remain agnostic about the data it transports (which is something I like with the fact to pass just a "payload" object).

Removing the unnecessary level could be another solution, but the lastModified could actually be useful to the hooks: where would you put it?
