### ISSUE TITLE
Don't version dist files on github

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto.js#358]
We should rather generate them before publishing to npm, as we do for kinto-client. Minified assets will only be available from npmcdn using the package bundled assets.

- [ ] Add `./dist` to `.gitignore`
- [x] Create a npm `publish-to-npm` command taking care of building libs files, dist files and running `npm publish`
- [ ] Update npm `publish-demo` command

**Comment by lavish205** [comment]
@n1k0 we can close this issue now :)

**Comment by n1k0** [comment]
Fixed by #374
