### ISSUE TITLE
Skip `importChange` if ETag did not change?

### ISSUE THREAD

**Issue by michielbdejong** [Kinto/kinto.js#376]
When listing a folder's content on remoteStorage, there is no way to filter by last modified timestamp. You have to list the whole folder content and compare record ETags one-by-one to see which records changed since the last time you synced each of them.

To support this, I would like to add [a check to see if the record's ETag actually changed remotely](https://github.com/michielbdejong/kinto.js/blob/23a1ea475bd7be4fab1c0ef891c08cfcfa7ce37c/src/collection.js#L147-L152). Is that OK, shall I create a PR for that?

**Comment by leplatrem** [comment]
This does not sound like a bad idea. However I wonder when this happens, since we are supposed to retrieve a list of changes from a particular local timestamp. Don't changes always have a different timestamp than the previously known one?

**Comment by michielbdejong** [comment]
When syncing with kinto-client as the Api, this will indeed not occur, because you already filter so that you only get records which are new. But I'm starting to use kinto.js as a more generic off-line first sync lib, injecting a remoteStorage client as the Api, and there I want to be able to give it an unfiltered list of records in response to `listRecords`.

**Comment by leplatrem** [comment]
Okay it makes sense then.

**Comment by leplatrem** [comment]
Could you please check that what we did #417 covers this use-case?
See https://github.com/Kinto/kinto.js/blob/254a5a1364ecd38251264323f4099099ce605b9d/src/collection.js#L149
Thanks!

**Comment by michielbdejong** [comment]
Unfortunately I had to stop working on the more generic off-line first sync lib I mentioned because of other priorities within Team Link, and I didn't try this out your patch practice because I don't remember where I had the code that needed it, but looks like it does the job yes, thanks! Will close this issue.
