### ISSUE TITLE
Synced Blob becomes empty object (`{}`)

### ISSUE THREAD

**Issue by domtallo** [Kinto/kinto.js#390]
If I `.create()` an object containing blobs, and then `.get()` or `.list()` the collection, everything's cool. But when I `.sync()` the collection, the Blobs become empty objects (`{}`). 

E.g. (pseudocode)
```
article = { title: title, blob: blob };
articles.create(article);

//...

articles.get(articleId)
  .then(res => console.log(res.blob)); // prints "Blob ..."

articles.sync()
  .then(console.log.bind(console));    // prints { ..., published: [{ title: title, blob: {} }], ... }

articles.get(articleId)
  .then(res => console.log(res.blob)); // prints "{}"
```

Every `.get()` or `.list()` after the `.sync()` returns `{}` instead of the stored Blob.

Does Kinto support blobs? Could it be that I have to enable via some config? 

P.S. Blob size is very small, so I'd exclude any bandwidth issues.

**Comment by n1k0** [comment]
Blobs are not serializable in JSON, so your best bet would be to send a string representation of the content here (eg using bas64 or eq.).

Note: if you're storing files, Kinto offers support for them through [kinto-attachment](https://github.com/Kinto/kinto-attachment), but which isn't supported by kinto.js just yet.

**Comment by Natim** [comment]
@domtallo did you manage to encode your blob's in base64? Can we close this issue?

**Comment by domtallo** [comment]
I did but I receive errors on sync about JSON parsing. I'm going to provide
more detail in a few hours, when I get to my PC.


Il lun 18 apr 2016, 15:04 Rémy HUBSCHER <notifications@github.com> ha
scritto:

**Comment by Natim** [comment]
Ok, if you could provide us with a way of reproducing the error that would be great.

**Comment by domtallo** [comment]
I'm gonna close this because I can't reproduce the JSON parsing issue I was having on sync anymore. 
Will reopen if issues re-emerge. Thank you for your support!

**Comment by Natim** [comment]
Thanks @domtallo do not hesitate to reopen in case it happens again :)
