### ISSUE TITLE
[fx-src] Pass FFx dependencies to loadKinto

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto.js#392]
The idea whould be to allow delegating the creation/retrieval of Gecko specific modules in Firefox itself and pass them to `loadKinto`.

Thoughts? 

Before:

```js
export default function loadKinto() {
  const { EventEmitter } = Cu.import("resource://devtools/shared/event-emitter.js", {});
  const { generateUUID } = Cc["@mozilla.org/uuid-generator;1"].getService(Ci.nsIUUIDGenerator);

  // Use standalone kinto-client module landed in FFx.
  const { KintoHttpClient } = Cu.import("resource://services-common/kinto-http-client.js");

  Cu.import("resource://gre/modules/Timer.jsm");
  Cu.importGlobalProperties(['fetch']);
  
  ...
```

After

```js
export default function loadKinto({fetch, generateUUID, Timer, EventEmitter, KintoHttpClient}) {
  ...
```

And in Gecko land:

```js
const { EventEmitter } = Cu.import("resource://devtools/shared/event-emitter.js", {});
const { generateUUID } = Cc["@mozilla.org/uuid-generator;1"].getService(Ci.nsIUUIDGenerator);
const { KintoHttpClient } = Cu.import("resource://services-common/kinto-http-client.js");
Cu.import("resource://gre/modules/Timer.jsm");
Cu.importGlobalProperties(['fetch']);

loadKinto({
  EventEmitter,
  generateUUID,
  KintoHttpClient,
  Timer,
  fetch
});
```

One of the most immediate benefit would be to not have any Firefox specific imports in there.

Thoughts? @leplatrem @mozmark

**Comment by leplatrem** [comment]
For `Timer` it does not look so obvious and should be splitted into `setTimeout`, `setInterval`...

Then in the `loadKinto` you'll have to pass the reference to those everywhere underneath, unless to assign them to some global :/

At first sight, appart from module loading optimization, I don't see too much value :blush:

**Comment by n1k0** [comment]
The underlying idea was to start writing unit tests for this now node-compatible code, but I realize we're still relying on the FirefoxStorage adapter which also has dependencies to FFx-only code.

Feel free to close if anything of this makes sense.
