### ISSUE TITLE
Get rid of deeper and its dependencies to Buffer and buffertools

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto.js#402]
The `deepEqual()` function that we need is a lot simpler than the one provided, since we only want to compare incoming records with simple attributes.

* [x] Write simple recursive object comparison
* [x] Remove `--ignore buffertools`
* [x] Include EventEmitter (and possible others)
* [x] Add `--bare` to dist commands (?) This could reduce the size of dist files.
* [x] Remove hack with Buffer mock in `fx-src/jsm_prefix.js`

* Related #400

**Comment by n1k0** [comment]
`deeper` has been removed in #406.

**Comment by n1k0** [comment]
Fixed by #406 and #407.
