### ISSUE TITLE
pushChanges is missing a case

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto.js#418]
The `then` block in https://github.com/Kinto/kinto.js/blob/d696e76dfba7f36a107f0d3a910cee142bbd39d7/src/collection.js#L854-L873 has a set of if-else-if blocks that aren't exhaustive. If we get something `resolved` which is not synced (`resolvedUnsynced.length != 0`), and our strategy isn't either `CLIENT_WINS` or `SERVER_WINS`, we fail to return anything at all. This caused me problems when I was trying to put together a fix for #414 and tried to mark a conflict as "resolved".

I'm not sure if we consider this case something that "can't happen". It seems like the only strategy this applies to is `MANUAL`, and we could assume that unsynced resolutions should never get to `pushChanges` in `MANUAL` because the conflicts stopped the sync. If this is how we want to hande this, I think we should put a default "else" case in `pushChanges` that throws a "can't happen" error, or at the very least add a comment explaining how someone got here and suggesting what they do to fix it.

**Comment by n1k0** [comment]
Yeah, the `else` cause missing here is puzzling. 

> we could assume that unsynced resolutions should never get to pushChanges in MANUAL because the conflicts stopped the sync

Indeed, and I feel then we could have bypassed the flow earlier, but maybe I'm missing a use case; It's strange to call `_handleConflicts` at all if we're in `MANUAL` mode. There's possibly something to refactor here...
