### ISSUE TITLE
resolve() should set status to "synced" or "updated"

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto.js#419]
According to @leplatrem on #417 and #414, 

>  * In resolve() mark as "synced" if conflict is resolved with remote version. "updated" otherwise.

Do this and add tests to prove it.

**Comment by glasserc** [comment]
How do we detect that the conflict was resolved with the remote version? `deepEqual`? `===`?

**Comment by n1k0** [comment]
`deepEqual`, as you can't compare objects with `===` as they're mutable and carry an identity (welcome to js btw!)

**Comment by Natim** [comment]
Another case to take into account is: https://github.com/Kinto/kinto-admin/issues/59 where we should mark a conflict as sync when the remote and local version are deep equals except for the last_modified value (in that case we should take the remote record last_modified value )
