### ISSUE TITLE
what is the true meaning of "created" and "updated"?

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto.js#456]
I thought created meant "we have it locally, but it doesn't exist on the remote server", and "updated" means "this record exists remotely, but we have changed it since then". However, while writing code for #455, I noticed that if you call `update()` on a `created` record, it becomes `updated`. This seems strange to me, since it doesn't exist on the remote server yet. I would expect it to remain "created" until it synced.

**Comment by leplatrem** [comment]
I think you are completely right. And we can call this a bug.
