### ISSUE TITLE
.sync() fails when record contains large string as a value

### ISSUE THREAD

**Issue by doplumi** [Kinto/kinto.js#457]
To replicate this issue:
1. Create a dummy record and `.sync()` it.
2. `.update()` the record with a large string (example below).
3. `.sync()` again.

The `SyncResultObject` will contain this error:

```
error: Object
  code: 400
  details:
    description: "Invalid JSON request body: Expecting value: line 1 column XXXXX (char XXXXX)"
    location: "body"
    name: null
  errno: 107
  error : "Invalid parameters"
  message : "body: Invalid JSON request body: Expecting value: line 1 column XXXXX (char XXXXX)"
```
#### Debugging

Patching the created record using the terminal works perfectly*, so the problem doesn't seem to be in `kinto` the server repo. Might be in `kinto-client` though. 
It seems like the error could be caused by the large string being truncated somewhere down the way, but the error object reports the sent object also where the string is reported in its entirety, and the JSON is even parsed correctly by Chrome dev tools. So, I am giving this up to you `¯\_(ツ)_/¯`
#### An example JPEG

All of the jpegs I tried so far give me the error. They're 256x256, about 50k. I'm posting one on [pastebin](http://pastebin.com/WsNHEdmG) as an example, so whoever wants can reproduce the issue.

P.S. For those of you who can't notice at sight, you can verify the base64 string is a correct jpeg by giving it to this [online converter](http://codebeautify.org/base64-to-image-converter). You're welcome.
---

(*): Beware that pasting the ~50kb string into the terminal will take a lot. I'd say about 40s on my i7 desktop machine.

**Comment by leplatrem** [comment]
Sorry, I haven't taken the time to investigate this. Did you find out something in the mean time ?

**Comment by vikassahu29** [comment]
@doplumi @leplatrem 

I tested this but wasn't able to reproduce it. Issue might be with the escaping of base64 string that you are doing.

### How I tested

1. In the demo app(That is there with the kinto.js library) - I pasted the complete base64 string in the textbox and submitted it
2. synced it
3. on done updated I appended the string thrice (modified some code for this)
4. synced it again

**Everything seems to work fine.**

**Comment by doplumi** [comment]
Thank you for taking the time to look into this.
I'm closing the issue since I am the only one who was affected. I haven't been using kinto for a while and a lot has changed since I opened it. I think kinto-server was still on version 3.0. 
I'll make sure to report back again should I notice this behavior again another time.
