### ISSUE TITLE
Is `collection.db` part of the pubic API?

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto.js#466]
Right now we have a concept of a transaction which is only available at the adapter layer and not at the collection layer. Although it's limited mostly to batch writes, it would still be useful for projects such as the WebExtensions work I'm doing. I would like to use it but I'm not sure if it's part of the public API or if we expect all access to go through the Collection API. What do you think?

**Comment by n1k0** [comment]
While not heavily documented, the adapter instance is part of the public API https://doc.esdoc.org/github.com/Kinto/kinto.js/class/src/collection.js~Collection.html

We may want to expose (and properly document) an higher level `Collection#batch` method though.

**Comment by glasserc** [comment]
Sounds good. Closing in favor of #467.
