### ISSUE TITLE
Safari only DataError: DOM IDBDatabase Exception 0: The data provided does not meet requirements

### ISSUE THREAD

**Issue by argyleink** [Kinto/kinto.js#524]
![screen shot 2016-08-23 at 12 32 19 pm](https://cloud.githubusercontent.com/assets/1134620/17906860/e45bd0d4-692d-11e6-9627-e7aca4b4aae8.png)

**Comment by n1k0** [comment]
Hmm, could you please provide more context about this error and the condition to reproduce? Ideally minimal sample code and/or reproduction steps :) Thanks!

**Comment by argyleink** [comment]
I can briefly describe it, I probably won't be making a fiddle or anything with repro... But we've built a pretty robust web app around Kinto, anywhere from 3-8 indexed db's get created per user, and all works great except when we try in Safari. We're not storing any crazy objects, 90% of them are very shallow and simple. 

The problem seems specifically with the sync function, since on app load, our data is pulled down and stashed into Safari fine, but the above error occurs before we get the `.list()` data from a set of collections. We sync anywhere between 2-5 collections to show a view, and the data is never returned for use, seems stuck in IDB. I've spent a decent amount of time this morning trying to debug it, since by the error message, it would seem like an issue with our data models. But from all my testing, the error occurs on even very simple data models, and is essentially inconsistent with what "data provided does not meet requirements" means in relation to our models. Also, since the data is present in the browser, I can only assume the write was fine, and that it's the read that's struggling. 

Do you have tests I can run in browser? 
Do you guys support Safari (their IDB support is pretty crappy)? 
Did my clues help at all, or will I need to build a fiddle to really prove the issue?

**Comment by n1k0** [comment]
> Do you have tests I can run in browser? 

Unfortunately we don't. That's probably something we should work on as the implementations may substantially vary, but our resources are sparse... so any help would be much appreciated on this front. I know saucelabs allows running code on several platforms and expose a convenient API to post some to their platform, would be matter of exporting the current mocha tests suite as an HTML runner against an actual browser IDB impl. (we only use a [pure js though spec compliant one](https://github.com/dumbmatter/fakeIndexedDB) atm).

> Do you guys support Safari (their IDB support is pretty crappy)?

We don't officially support it (I think I've never tested kinto.js against it myself tbh), and I suspect this won't be P1 anytime soon, except if the community is willing to offer some help here...

> Did my clues help at all, or will I need to build a fiddle to really prove the issue?

Not very much I'm sorry to say. Does the [demo](https://kinto.github.io/kinto.js/) work with Safari? Note that I can't really test myself (and more generally fiddle with Safari) as I'm a linux user :/

**Comment by Natim** [comment]
I though that Kinto.js wasn't working with Safari because of fetch not being supported, isn't it the case?

**Comment by n1k0** [comment]
> I though that Kinto.js wasn't working with Safari because of fetch not being supported, isn't it the case?

Its kinto-http.js dependency uses the [isomorphic-fetch](https://www.npmjs.com/package/isomorphic-fetch) polyfill.

**Comment by Natim** [comment]
@argyleink would you be willing to help on adding Safari support for Kinto.js?

**Comment by argyleink** [comment]
**Good news**, the demo page works in Safari on desktop and Safari on iOS. So I can pretty confidently declare that the bug is in our Kinto usage. We may be overloading the stores, or something.. Not sure. It's only Safari though that complains, so I guess the contention between Kinto and our app can come to an end, and so begins the contention between Safari's IDB support and our app's needs. 

So, until further notice, I'll close this issue, and only reopen it if I can supply proper reproduction steps in Safari. Sorry to have logged an issue, I thought it was more than a hunch, but I feel corrected.

**Comment by argyleink** [comment]
ah! i never hit sync in the demo, and boom, that's all it took to get the error in Safari desktop and mobile. so the issue is in the sync logic.. 

![screen shot 2016-08-24 at 10 03 57 am](https://cloud.githubusercontent.com/assets/1134620/17940037/22b9cf3e-69e2-11e6-81fc-586663640ae0.png)


while i feel qualified to help you with kinto and the IDB usage in Safari, I'm not confident that I would contribute quality code, it would naturally be hacky and full of pooey workarounds. BUT, maybe the issue isnt with IDB so much, and it's more with whatever is happening in the sync logic. i'd be happy to test our app on a beta version of the lib, to help verify a fix or 2. but i'm timid to commit time to help resolve the issue. 

what else can i do to help? =)

**Comment by Natim** [comment]
Apparently it seems to be related to that: http://stackoverflow.com/questions/17131015/why-is-this-indexeddb-put-command-failing-error-dataerror-dom-idbdatabase-exc

@argyleink I don't think there is a lot of code to write, we just need to find a way for ``put`` to work across different browsers. 

More info about the exception here: https://www.w3.org/TR/IndexedDB/#exceptions

**Comment by Natim** [comment]
@argyleink Could you try this branch #527?

**Comment by leplatrem** [comment]
Or this JSFiddle:  http://jsfiddle.net/ashustariov/Wk7VF/28/

Also, which version of Safari ? 

Related?  https://github.com/pouchdb/pouchdb/issues/5572

**Comment by aegaas** [comment]
We just tried the fix-safari branch in MacOS 10.11 with Safari 9.1.2 got the same error:

```
{
  "ok": false,
  "lastModified": 1472113378860,
  "errors": [
    {
      "type": "incoming",
      "message": "DataError: DOM IDBDatabase Exception 0",
      "stack": "put@[native code]\nupdate@http://127.0.0.1:8080/kinto.js:938:1415\nimportChange@http://127.0.0.1:8080/kinto.js:944:1270\nhttp://127.0.0.1:8080/kinto.js:944:9212\nmap@[native code]\nhttp://127.0.0.1:8080/kinto.js:944:9180\nhttp://127.0.0.1:8080/kinto.js:938:4802\nhttp://127.0.0.1:8080/kinto.js:938:2599"
    }
  ],
  "created": [],
  "updated": [],
  "deleted": [],
  "published": [],
  "conflicts": [],
  "skipped": [],
  "resolved": []
}```

**Comment by argyleink** [comment]
some goods news though, the kinto demo works in iOS 10. So we're currently discussing a bug that will soon only be on older version of safari, which has many known IDB bugs. just wanted to throw that good news nugget into the mix here. 

also, the changes made in the branch, are very similar to attempts I made the other morning after doing some research as well. no combinations of put seemed to pacify the whiney and wrong safari implementation. but, i'm also no pro at IDB, so I'm not super confident that my attempts were meaningful.

**Comment by aegaas** [comment]
A little update. We began locking down npm and bower versions yesterday on our project and learned that we might be facing a regression from kinto.js 3.0.0 and kinto.js 3.1.0. I have confirmed with the demo that 3.0.0 works great in safari and 3.1.0 is broken in safari.

We have now locked our version of kinto.js to 3.0.0 and are unblocked, but it seems possible that we can bring safari support back to master somehow. Hope this helps!

**Comment by Natim** [comment]
Good to know thanks, let's improve #527 to make sure we fix the matter in 3.1.x

**Comment by Natim** [comment]
So basically we broke support for Safari when we [add IDB transaction in the mix.](https://github.com/Kinto/kinto.js/compare/v3.0.0...v3.1.0#diff-1ea8641b3121dd24ac71a35bb03e6e23)

**Comment by ptgamr** [comment]
I'm having this issue too

**Comment by argyleink** [comment]
![gif](https://media.giphy.com/media/nXxOjZrbnbRxS/giphy.gif)
