### ISSUE TITLE
investigate using permanent storage for IndexedDB adapter

### ISSUE THREAD

**Issue by elelay** [Kinto/kinto.js#526]
This way there is no limit on the DB size.
I keep hitting the Quota Exceeded error when I'm low on free space (< 700M) and sync a biggish db.

https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/open#Example
in [src/adapters/IDB.js:145](https://github.com/Kinto/kinto.js/blob/master/src/adapters/IDB.js#L145)

```
const request = indexedDB.open(this.dbname, {version: 1, storage: "persistent"});
```

This generates a prompt to the Firefox user, so it could be an option in the Kinto.js api.
I don't know if it's supported on other browsers.

**Comment by leplatrem** [comment]
This is specific to Firefox [according the docs](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Different_types_of_data_storage), but it is perfectly ok to add it if it doesn't harm other platforms!

**Comment by elelay** [comment]
It would be easy to put it into adapterOptions of the Kinto constructor, but what do we do browsers not supporting it?
 - I don't know how to do feature testing for it;
 - browser sniffing would check for "gecko > 26";
 - or is it OK to let the application determine when to pass the option use it when it's there (it feels wrong because we hide other IndexedDB details but it's the easiest) ?
 - the [spec](https://www.w3.org/TR/IndexedDB/#widl-IDBFactory-open-IDBOpenDBRequest-DOMString-name-unsigned-long-long-version) doesn't specify what to do if the 2nd argument is not a long. Otherwise we could try with storage name + version,  catch any exception and fallback to just the version.

**Comment by leplatrem** [comment]
Apparently this has changed in the meantime, and can be done outside kinto.js using the Storage API [0]

```js
if (navigator.storage && navigator.storage.persist)
  navigator.storage.persist().then(function(persistent) {
    if (persistent)
      console.log("Storage will not be cleared except by explicit user action");
    else
      console.log("Storage may be cleared by the UA under storage pressure.");
  });
}
```

I propose to close this. Please reopen if I'm wrong!

[0] https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Browser_storage_limits_and_eviction_criteria#Different_types_of_data_storage
