### ISSUE TITLE
optimisation: apply collection.list() filters to each document in the IDB adapter, not to the full array

### ISSUE THREAD

**Issue by elelay** [Kinto/kinto.js#534]
Searching through a big collection (8k records) is slow and allocates a lot of memory.
I attribute it to the fact that a big part of the collection is loaded in memory, when not searching by id, _status, last_modified.
What would be nice would be to apply filters to each document when it is fetched (in [IDB.js](https://github.com/Kinto/kinto.js/blob/master/src/adapters/IDB.js#L19).

**Comment by leplatrem** [comment]
If I'm not mistaken, this is very related to #66 

We could be more explicit about this limitations in the docs (give order of magnitude): http://kintojs.readthedocs.io/en/latest/limitations/#in-memory-filteringordering

**Comment by elelay** [comment]
I think filtering as you go is a lower hanging fruit than indexes (doesn't require incrementing the IDB version number, etc.).
I'll propose code in a PR for filtering as you go this week.

**Comment by leplatrem** [comment]
Great! 👍
