### ISSUE TITLE
Failed to execute 'delete' on 'IDBObjectStore' exception while syncing

### ISSUE THREAD

**Issue by ochameau** [Kinto/kinto.js#540]
I'm used to have this exception on Chrome for Android, it took me a while to debug that via remote devtools.
I'm not sure it has anything to do with Chrome or android, I imagine it has to do with the state that exists on the device.

I traced this exception back to this code:
https://github.com/Kinto/kinto.js/blob/3630426125a04650069f87d2461a8dc62fc2a82a/src/collection.js#L928
```
 transaction.delete(record.id);
```
Here, record.id is undefined.  record is just `{ deleted: true }`.

**Comment by ochameau** [comment]
It is again related to kinto-http:
https://github.com/Kinto/kinto-http.js/blob/0bdcbdb98e157df8157f061b7c60a949751ace94/src/batch.js#L24
`response.status` is 404.
`response.body` here is:
`{ errno: 110, code: 404, error: "Not found" }`

Such response ends up introducing later in the codepath the record.id being null.

**Comment by leplatrem** [comment]
Thank you very much for reporting (and tracking!) this bug!

**Comment by leplatrem** [comment]
Oh I tracked it and it was obvious (*and easy to fix*)! I wonder how we never come into this :((

BTW here is the error I have from the test suite :) Maybe it's what #524 is about! /cc @magopian @Natim 

```
DataError: Data provided to an operation does not meet requirements.
      at validateKey (node_modules/fake-indexeddb/lib/validateKey.js:35:15)
      at delete (node_modules/fake-indexeddb/lib/FDBObjectStore.js:107:35)
      at Object._delete [as delete] (IDB.js:436:7)
      at collection.js:937:17
      at Array.map (native)
      at collection.js:936:11
      at IDB.js:288:22
```
```

**Comment by Natim** [comment]
You are teasing, what is the fix?

**Comment by ochameau** [comment]
> Oh I tracked it and it was obvious (and easy to fix)! I wonder how we never come into this :((

I'm not doing anything much fancy with kintojs. Don't take it personally, but are you dogfooding your lib ?
(From what I saw, there is various real world apps here and there, so I think you do)
My two bug reports are about some really simple usage of the lib with real usage of sync.
It would be fantastic if you could relate this issue with the other I reported over #522 and see in which particular area the dogfooding fails.

**Comment by Natim** [comment]
@ochameau It is going to change soon with webextensions but for now in production we are not synchronizing with IndexedDB but just with SQlite3 in Firefox and it is a one way sync.

Don't think Kinto.js or Kinto or any program ever actually is supposed to be stable or bug less. Developing application is a process, filling bug is the right thing to do and fixing it as well. Each day the ecosystem got better because of people like you using it, finding bug and reporting them so thank you :)

**Comment by leplatrem** [comment]
The two bugs are indeed very related to the fact that the client returns something that is not a record.

I believe that these are regressions that were introduced when we splitted the http layer originally in this repo to a separate client library.

I will provide patches. With my current approach, the `skipped` attribute in the sync result remains completely useless. But I want to do better and provide the particular record that lead to a 404. This might lead to a new release of kinto-http.js too.

Thanks for your inputs and patience ;)

**Comment by ochameau** [comment]
Oh! I didn't realized kinto was using another backend and also that you were so focused on Firefox usage.
That explains a lot.

Could you ping me once there is the new build so that I could resume playing with kinto?

**Comment by Natim** [comment]
Yes sure :)
