### ISSUE TITLE
Add deleteAll() method on collection

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto.js#556]
The available `clear()` method would wipeout the local data but won't delete records remotely.

We would need a method to delete all records locally and delete records remotely on sync...

This method on the collection class would set the «sync status» of its records to `deleted`, as if they would have been individually deleted with `deleteRecord()`
https://github.com/Kinto/kinto.js/blob/833a879b3aecd6c0abc407499eff29358b35a078/src/collection.js#L604

A test should be added here:
https://github.com/Kinto/kinto.js/blob/833a879b3aecd6c0abc407499eff29358b35a078/test/collection_test.js#L1169
That:
- creates some records in setup
- calls the new `deleteAll()`
- verifies that every records are still here but marked as `deleted` (ie. virtually deleted) using something like:
```js
articles.list(
            { filters: { _status: "deleted" } },
            { includeDeleted: true }
);
```

I think we may also want to check that the `deleteAll()` method emits an event.

**Comment by hd719** [comment]
Hello I am new to open source, it this still open?

**Comment by glasserc** [comment]
Yes, as far as I know, please feel free to work on it.

**Comment by markellisdev** [comment]
If @hd719 is not currently working on this, I'd like to have a go. @hd719 are you still actively working on this issue?

**Comment by hd719** [comment]
All you bro.

**Comment by markellisdev** [comment]
👍🏼

**Comment by markellisdev** [comment]
I'm attempting this, but got errors when trying to use with Node 0.12x environment, indicating I needed Node 4x or higher, so I used 4.3.0, which I have for another project. This worked fine with npm install.

However, when initially attempting to test, I get errors at the `eslint src test`

```
 ~/workspace/kinto.js <master> ✗ source ./venv/bin/activate
(venv) [] ~/workspace/kinto.js <master> ✗ npm test

> kinto@9.0.2 test /Users/markellis/workspace/kinto.js
> npm run lint && npm run test-nocover


> kinto@9.0.2 lint /Users/markellis/workspace/kinto.js
> eslint src test

sh: eslint: command not found

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/markellis/.nvm/versions/node/v4.3.0/bin/node" "/Users/markellis/.nvm/versions/node/v4.3.0/bin/npm" "run" "lint"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! kinto@9.0.2 lint: `eslint src test`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the kinto@9.0.2 lint script 'eslint src test'.
npm ERR! This is most likely a problem with the kinto package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint src test
npm ERR! You can get their info via:
npm ERR!     npm owner ls kinto
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/markellis/workspace/kinto.js/npm-debug.log
npm ERR! Test failed.  See above for more details.

(venv) [] ~/workspace/kinto.js <master>
```
Can you help me through this @leplatrem ?

**Comment by glasserc** [comment]
It looks like `eslint` isn't installed. Did you do `npm install`?

**Comment by markellisdev** [comment]
I did, yet when I try `which eslint`, it says `eslint not found`.

I noticed in the docs, it says use `NodeJS v0.12x`, yet in `package.json` the engine is
```
  "engines": {
    "node": ">=6"
  },
```
Could this have something to do with it? I've tried Node `v4.3.0` and `v0.12.18`

**Comment by glasserc** [comment]
Sure, that could have something to do with it. The `eslint` "executable" is in `node_modules/.bin/`, and `npm` is supposed to be smart enough to run things from there automatically when it's running a script. Maybe that was added after Node v4?

**Comment by markellisdev** [comment]
After reading the above in `package.json` I tried `v7.10.0` which seemed to eliminate that error yet generated another,  `sh: babel-node: command not found`. This one did actually create a debug.log though. However, I can't include it here. Maybe I'll convert to a txt file.

May I submit a PR to change the docs to reflect it requires `[NodeJS v6 or greater]`?

**Comment by glasserc** [comment]
Sure!

`babel-node` comes from `babel-cli`, which again should have been installed from `package.json` when you did `npm install`. Maybe try rerunning `npm install` with the new node?

**Comment by markellisdev** [comment]
Thanks @glasserc . I deleted `node_modules` and ran `npm install` again. I've got tests running now and I'm working on completing this issue.

**Comment by nirabhratapaswi** [comment]
I am new to opensource and I would like to try out this issue, if you are not working @glasserc can I start with it @leplatrem ?

**Comment by leplatrem** [comment]
@nirabhratapaswi welcome!

I guess we can consider this issue available for you (no news since last July)

First, before changing any line of code, you need to get a local environment working (ie. be able to run the automatic test suite successfully) Please follow these instructions: http://kintojs.readthedocs.io/en/latest/contributing/
If something does not work, seems unclear or outdated, please come back here and shout it out :) Even if you're not sure whether it comes from you or the docs.

Once you have that, you can start investigating the issue and what has to be done. I'll update the original issue description to give more details :)

Good luck, and enjoy!

**Comment by nirabhratapaswi** [comment]
Thankyou, I was trying to run the test (npm test) but it seemed to fail for various reasons. Even after correcting a few, I am stuck in this fail, can you help?

1) Integration tests
       Deprecated protocol version
         Soft EOL
           should warn when the server sends a deprecation Alert header:
     Error: HTTP 410 Gone: Service deprecated (The service you are trying to connect no longer exists at this location.)
      at HTTP._callee$ (node_modules/kinto-http/lib/http.js:184:23)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
      at node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by nirabhratapaswi** [comment]
Apart from the above (npm test command), the other npm tests passed, so I went ahead and got an idea of the functioning of the library. To be sure, in src/collection.js, under export default class Collection, there are methods for delete(), deleteAny(), clear(), and a deleteAll() needs to be implemented which will delete a collection locally and on the remote simultaneously! Is something like this is needed?

```javascript
async deleteAll(syncOptions) {
    const records = await this.list();
    await records.forEach((record) => {
      return this.delete(record.id);
    });
    await this.sync(syncOptions);
  }
```
and called as -
```javascript
var syncOptions = {
    remote: "https://kinto.dev.mozaws.net/v1/",
    headers: {Authorization: "Basic " + btoa("user:pass")}
  };
tasks.deleteAll(syncOptions);
```

**Comment by nirabhratapaswi** [comment]
@leplatrem ??

**Comment by Natim** [comment]
@nirabhratapaswi Don't except answers from us during the week-end.

I guess the first thing to do is to write a test that verifies that as soon as we call deleteAll all local records are marked as deleted so that they will be effectively removed during the next sync call.

**Comment by glasserc** [comment]
The integration tests failing is a bit strange. What kinto are you running, how did you install it, and is there any other Kinto running on your computer at the same time?
