### ISSUE TITLE
Provide a «key-value store» ID schema

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto.js#558]
The default id schema generates uuid. We could provide another one, that would be useful for when using kinto.js as a key value store:
- its `generate()` method throws error
- its `validate()` would always return true

**Comment by d1ndra** [comment]
I'd like to work on this if anybody isn't. Any help regarding where I should start?

**Comment by glasserc** [comment]
Go for it! We usually advise a somewhat TDD-based workflow where you write tests that demonstrate the API you would like to support, followed by implementations that make the tests pass. I think the best API would be one that exposed some ID schemas in the same module as whatever else most users import. There's already a UUID schema that could get exported at the same time.

**Comment by Jonathansw** [comment]
Is this still open to be worked on?

**Comment by glasserc** [comment]
Yes! I think the approach I wrote about above is still valid, although I should withdraw the remark that there's already a UUID schema, since the one that is there relies on Firefox internals.

**Comment by AndresMurguido001** [comment]
If this is still open id like to give it a shot. But a little more info would be helpful. If im understanding this right, there should be an option to get and set keys like a hashtable and just use autoIncrement?

**Comment by aqumus** [comment]
@glasserc Would be good to close this issue if the merged PR is working as expected
