### ISSUE TITLE
I would like a Kinto#resetSyncStatus

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto.js#567]
This would operate on all collections in the local database.

**Comment by n1k0** [comment]
In the case of IDB, that would mean keeping track of all collections db names handled by the library (solely relying on the name pattern seems fragile).

**Comment by glasserc** [comment]
For my purposes, it would be good enough for it to just work in the Firefox storage.

**Comment by glasserc** [comment]
With #562, it seems like this would be better suited to being as part of the FirefoxStorage class which will presumably be in Gecko, so I'll close this until someone else wants it.

**Comment by leplatrem** [comment]
If it's feasible with indexeddb then no problem to expose that at the collection level!

**Comment by leplatrem** [comment]
Note: https://bugzilla.mozilla.org/show_bug.cgi?id=934640
