### ISSUE TITLE
Use LocalForage as storage adapter?

### ISSUE THREAD

**Issue by lgleim** [Kinto/kinto.js#575]
Hi, I'm looking into using Kinto + Kino.js for an offline first mobile application. I'm planning on using Ionic/Cordova for the project and have previously been playing around a lot with PouchDB. One issue that keeps coming up is [storage limitations](https://www.html5rocks.com/en/tutorials/offline/quota-research/#toc-overview) and the issue, that [iOS does not support IndexedDB](https://cordova.apache.org/docs/en/latest/cordova/storage/storage.html#indexeddb). 
PouchDB solves this by choosing from various different storage backends depending on the environment. In order to circumvent the storage limits in Cordova deployments the [Cordova SQLite storage plugin](https://github.com/litehelpers/Cordova-sqlite-storage/) or [Cordova SQLite Plugin 2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) may be used. 
I have previously also heard a lot about [localForage](https://github.com/localForage/localForage), also developed by Mozilla, which allows to adaptively select a storage backend depending on the environment and for which a [cordova sqlite storage driver](https://github.com/thgreasi/localForage-cordovaSQLiteDriver) exists. 

Would it be possible to provide a storage adapter based on LocalForage or does it lack crucial features such as indexing?

**Comment by lgleim** [comment]
This may be related to https://github.com/Kinto/kinto.js/issues/16#issuecomment-130261566

**Comment by lgleim** [comment]
After stumbling on https://mail.mozilla.org/pipermail/kinto/2016-March/000094.html and https://mail.mozilla.org/pipermail/kinto/2016-March/000095.html I guess localForage is not really an option.
Alternatively I found the https://github.com/ABB-Austin/cordova-plugin-indexeddb-async plugin. This probably solves any remaining issue that might not be solved using the default innodb shim. The question that remains for me is how to deal with hitting the storage limits of various platforms. Any insights?

**Comment by lgleim** [comment]
After stumbling on https://mail.mozilla.org/pipermail/kinto/2016-March/000094.html and https://mail.mozilla.org/pipermail/kinto/2016-March/000095.html I guess localForage is not really an option.
Alternatively I found the https://github.com/ABB-Austin/cordova-plugin-indexeddb-async plugin. This probably solves any remaining issue that might not be solved using the default innodb shim. The question that remains for me is how to deal with hitting the storage limits of various platforms. Any insights?

**Comment by leplatrem** [comment]
Hi!

Thank you for your detailed feedback!

> provide a storage adapter based on LocalForage

As you read on the ML, it is possible to write a LocalForage adapter. It won't support transaction though.

> how to deal with hitting the storage limits of various platforms

Maybe implementing a WebSQL adapter — like PouchDB — would be a valid approach here.
But what is the order of size of your data?

**Comment by lgleim** [comment]
The size of data (without attachements, which I plan to load on demand) is in the range of more then 5mb, potentially more then 50mb but nowhere near 500mb. 
I am aware of the [limitations with the query api](https://kintojs.readthedocs.io/en/latest/limitations/#in-memory-filteringordering) however the same is true for PouchDB. I am not sure of couchbase lite solves this in a better way but since it is also based on sqlite internally I do not expect much better performance either.

Instead of reimplementing with LocalForage I do think it is much easier to hack the [cordova-plugin-indexeddb-async](https://github.com/ABB-Austin/cordova-plugin-indexeddb-async) to always fallback to an sqlite-based backend (cf. https://github.com/ABB-Austin/cordova-plugin-indexeddb-async/issues/2).

**Comment by lgleim** [comment]
I'm closing this for now. Feel free to reopen if this becomes relevant again.

**Comment by kartikagarwal1993** [comment]
@lgleim Hey, I am also trying to solve a similar problem. Could you tell how did you finally overcome the memory limitations? Thanks!
