### ISSUE TITLE
Remove async/await transpilation for Firefox build

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto.js#591]
It landed on nightly

**Comment by leplatrem** [comment]
Hum, removing ` "transform-async-to-generator", "transform-runtime"`

```
SyntaxError: /home/mathieu/Code/Mozilla/kinto.js/src/collection.js: Unexpected token (394:8)
  392 |    * @return {Promise}
  393 |    */
> 394 |   async clear() {
      |         ^
  395 |     await this.db.clear();
  396 |     await this.db.saveLastModified(null);
  397 |     return {data: [], permissions: {}};
    at Parser.pp.raise (/home/mathieu/Code/Mozilla/kinto.js/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/home/mathieu/Code/Mozilla/kinto.js/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.expect (/home/mathieu/Code/Mozilla/kinto.js/node_modules/babylon/lib/parser/util.js:83:33)

```

**Comment by glasserc** [comment]
I'm excited to do this, but I've heard from some people that I should be patient because there is still some fear that it will get backed out or altered. See e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1314176#c6.

**Comment by leplatrem** [comment]
The whole code base was converted to async await. We can do it :)

**Comment by leplatrem** [comment]
This was fixed:
https://searchfox.org/mozilla-central/rev/efce4ceddfbe5fe4e2d74f1aed93894bada9b273/services/common/kinto-offline-client.js
