### ISSUE TITLE
Support remotetransforming deletes into record updates

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto.js#638]
When a record is deleted locally, kinto.js sends that local deletion as a DELETE to the remote server. However, if you're using a RemoteTransformer to encrypt the records, you probably want to encrypt deletes as well so that you don't leak information about the fact that a delete occurred (or to store information that a normal tombstone wouldn't). Right now we don't seem to support this; records that end up in `toDelete` get the transformer run over them, but whatever the transformer returns is still passed to `batch.deleteRecord`. It would be better if we could turn records from `toDelete` to `toSync`.

**Comment by Natim** [comment]
Unfortunately, I don't think that the Kinto server let you encrypt the deleted record payload :(
