### ISSUE TITLE
Unknown plugin "transform-object-rest-spread"

### ISSUE THREAD

**Issue by screendriver** [Kinto/kinto.js#649]
I installed `kinto` with [yarn](https://yarnpkg.com) and build my project with [webpack](https://webpack.js.org/). Unfortunately I get following error when I include kinto in my build with `import kinto from 'kinto';`:

```
ERROR in ./~/kinto/lib/index.js
Module build failed: ReferenceError: Unknown plugin "transform-object-rest-spread"
specified in "/Volumes/Foo/Development/bar/node_modules/kinto/.babelrc.env.development"
at 0, attempted to resolve relative to "/Volumes/Foo/Development/bar/node_modules/kinto"
```

If there is any more information that I should provide please let me know.

**Comment by screendriver** [comment]
I've got it working on my machine. I had to add `babel-plugin-transform-decorators-legacy`, `babel-plugin-transform-object-rest-spread` and `babel-plugin-transform-runtime` to my dev dependencies. Luckily my project is set up with Babel and not with other transpilers.

Hmm I don't know if it's a good idea to force consuming projects to add Kinto internal dev dependencies so that it can be referenced 🤔

**Comment by glasserc** [comment]
It looks like we're transpiling everything in the `build` script, and if I understand correctly, that's what's getting published using `npm publish` -- `.npmignore` includes src/, for example. I'm not super familiar with the JS ecosystem, though, so do you see anything else missing? It's possible that everything is correct but that I just somehow didn't run the right commands to upload a specific release.

**Comment by dstaley** [comment]
We're no longer using Babel, so I'm going to close this.
