### ISSUE TITLE
Support collection metadata sychronization

### ISSUE THREAD

**Issue by gabisurita** [Kinto/kinto.js#666]
From slack: I think it would be nice to allow to fetch and store a collection metadata using  kinto.js. 

A good use case for that would be integrating [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form).

**Comment by leplatrem** [comment]
How would the API look like?

For readonly, a `collection.metadata` attribute with the content of `/buckets/bid/collections/cid`  would be enough. It would be:
* synced to storage on pull
* fetched from storage on collection instanciation

For bidirectional sync, `collection.getData()` and `collection.setData()` could do it, but we have to find a nice design for the conflicts etc.
