### ISSUE TITLE
Use webpack for Gecko module?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto.js#738]
Using NPM Libraries in Firefox via Webpack http://www.mkelly.me/blog/using-npm-libraries-in-firefox-via-webpack/

**Comment by glasserc** [comment]
I don't think this article is relevant to our use case. We don't use a lot of JavaScript libraries from the npm ecosystem, and we aren't building an add-on. We have a pretty decent setup with browserify and I don't see any advantage to webpack itself. Closing
