### ISSUE TITLE
Tutorial : how to serve the demo ?

### ISSUE THREAD

**Issue by atopus** [Kinto/kinto.js#784]
From https://kintojs.readthedocs.io/en/latest/tutorial/

> And that's it. You should see something like this on http://localhost:3000:

How ?

I cloned the repo with the demo - no app.js nor server launching script.

I then tried to attach an express server in order to make it work. Got :

>  Uncaught ReferenceError: regeneratorRuntime is not defined

Thanks in advance for any piece of advice.

**Comment by Natim** [comment]
you right you need to use `npm run demo`

**Comment by glasserc** [comment]
Hi, the `regeneratorRuntime` issue might be related to Kinto/kinto-http.js#260, which just got released in kinto-http v4.4.1. Could you npm install that and try again?

**Comment by atopus** [comment]
Ok. Everything is resolved by running `npm run demo`.

Thanks !
