### ISSUE TITLE
Expose last_modifieds in the "server was flushed" exception

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto.js#802]
Bugs like https://bugzilla.mozilla.org/show_bug.cgi?id=1416255 could be made a bit easier if we expose the last_modified we had, as well as the last_modified the server had, when we raise the "server was flushed" exception.

**Comment by lexcorp16** [comment]
Hi @glasserc I would like to take a look at this. This is my first attempt to contribute to open source and I would be glad if you could point me in the right directions. Thanks

**Comment by glasserc** [comment]
Hi @lexcorp16, thanks for your interest! kinto.js implements an algorithm to "sync" data to and from the server. It works by tracking what has changed on the client and sending that, and asking what has changed on the server and receiving that. The main entry point is the `sync()` method in collection.js (https://github.com/Kinto/kinto.js/blob/76246b3c9abfc6fb668d747c4ca2755767cbaa85/src/collection.js#L1193).

In the internals of this method, sometimes we encounter a situation where the server tells us that nothing has changed, but responds in a way that indicates that something *has* changed. This can happen on the "dev" server (described at http://kinto.readthedocs.io/en/stable/tutorials/install.html#run-kinto-mozilla-demo), which gets wiped every morning. When it gets wiped, it will tell the client that there are no records which have changed (because there are no records), but the server will still seem "updated" (because it was wiped).

We throw an exception when this happens. I'm not sure exactly where this behavior originated but I've heard people say it's to try to help them debug strange syncing behavior on the dev server (because once data gets wiped, it's hard to "sync" anything). It's also helped us spot data loss issues in the Kinto server (for instance Kinto/kinto#1209). The exact line is:

https://github.com/Kinto/kinto.js/blob/76246b3c9abfc6fb668d747c4ca2755767cbaa85/src/collection.js#L975

We sometimes see this error in the chrome.storage.sync API in Firefox, which is implemented using this library. I'm concerned that it represents another data loss bug, or something even stranger, in the Kinto server, but it's hard to debug because all it says is "Server was flushed". I was thinking that it would be good for the error message to include some of the facts that led kinto.js to throwing this exception. In particular, I guess the lastModified from the client as well as the one the server responded with would be good. At least in the chrome.storage.sync case, this might indicate that an error recovery path was working, or not working.

Hope this helps! Feel free to ask on IRC or Slack if you need more help! (I'm usually on during the week.)

**Comment by neuroleptic** [comment]
Hey @lexcorp16, are you still working on this? If not, I can work on it.

**Comment by lexcorp16** [comment]
Hey @neuroleptic, please go ahead. Have been unavailable for quite some time now.

**Comment by aqumus** [comment]
Maintainer could we close this issue if the fix for it is merged and working? I was just browsing for OSS open issues for contribution and stumbled upon this one but looks like this is already fixed?
