### ISSUE TITLE
Rewrite documentation examples to async / await 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto.js#817]
We have stuff like:

```js
articles.list({filters: {_status: "created"}, order: "rank"})
  .then(console.log.bind(console));
```

...it would be easier to just have:

```js
await articles.list({filters: {_status: "created"}, order: "rank"});

**Comment by alexisllamas** [comment]
Hi @leplatrem, is fine if I work in this?

**Comment by leplatrem** [comment]
Yes of course!

**Comment by sanchitbansal10** [comment]
@leplatrem  whats the status..Is this issue open to work on

**Comment by cyrilledjdj** [comment]
Duplicate of #858

**Comment by cmgonzales** [comment]
is this issue close?

**Comment by glasserc** [comment]
No, there are still lots of places in the documentation which remain to be rewritten to `async`/`await`.

**Comment by cmgonzales** [comment]
@glasserc i’m would like to try to work on these if it’s ok

**Comment by bael-666** [comment]
Hi, can I also work on this?

**Comment by leplatrem** [comment]
Yes, of course!

**Comment by bael-666** [comment]
Are there any works that need to be done? I'm reviewing the the api.md and it seems already updated.  I will check on it more.

**Comment by Natim** [comment]
Yes it seems that at least the documentation doesn't contains any `.then` or `.catch`

**Comment by leplatrem** [comment]
Well the tutorial does https://kintojs.readthedocs.io/en/latest/tutorial/

**Comment by paullaffitte** [comment]
Hi, I would like to work on it too, could I?

**Comment by leplatrem** [comment]
Thanks but @Aebrathia did most of it... Are you interested in fixing easy-picks? There are a few in https://github.com/Kinto/kinto-http.js/issues if you want :)
