### ISSUE TITLE
Rename loadDump() to importBulk()? 

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto.js#872]
As @peterbe commented, the wording `loadDump()` is not entirely intuitive. Load let us think it loads into memory or something.

I suggest to we rename the method to `importBulk()` (and add deprecation to the old one)

**Comment by zakaluka** [comment]
I've put up a first attempt at this change - #875

**Comment by maniac-tech** [comment]
I see that the solution @zakaluka had written has been accepted and merged into master. In that case, @leplatrem can you update the Issue, and close it?

**Comment by leplatrem** [comment]
Oh yes! thank you for the heads up!
